-- ==============================================================================
-- FinanceUP - BIST Stocks Full Company Names Update Script
-- Bu scripti Supabase SQL Editor'da çalıştırarak 'stocks' tablosundaki 'name'
-- alanlarını şirketlerin resmi ve uzun unvanlarıyla güncelleyebilirsiniz.
-- ==============================================================================

UPDATE public.stocks SET name = 'A1 Capital Yatırım Menkul Değerler' WHERE symbol = 'A1CAP.IS';
UPDATE public.stocks SET name = 'A1 Yenilenebilir Enerji' WHERE symbol = 'A1YEN.IS';
UPDATE public.stocks SET name = 'Acıselsan Acıpayam Selüloz' WHERE symbol = 'ACSEL.IS';
UPDATE public.stocks SET name = 'Adel Kalemcilik' WHERE symbol = 'ADEL.IS';
UPDATE public.stocks SET name = 'Adese Gayrimenkul Yatırım' WHERE symbol = 'ADESE.IS';
UPDATE public.stocks SET name = 'Adra Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'ADGYO.IS';
UPDATE public.stocks SET name = 'Anadolu Efes Biracılık ve Malt Sanayii' WHERE symbol = 'AEFES.IS';
UPDATE public.stocks SET name = 'Afyon Çimento' WHERE symbol = 'AFYON.IS';
UPDATE public.stocks SET name = 'AgeSA Hayat ve Emeklilik' WHERE symbol = 'AGESA.IS';
UPDATE public.stocks SET name = 'AG Anadolu Grubu Holding' WHERE symbol = 'AGHOL.IS';
UPDATE public.stocks SET name = 'Agrotech Yüksek Teknoloji' WHERE symbol = 'AGROT.IS';
UPDATE public.stocks SET name = 'Atakule Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'AGYO.IS';
UPDATE public.stocks SET name = 'Ahlatcı Doğal Gaz Dağıtım' WHERE symbol = 'AHGAZ.IS';
UPDATE public.stocks SET name = 'Ahlatcı Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'AHSGY.IS';
UPDATE public.stocks SET name = 'Akbank T.A.Ş.' WHERE symbol = 'AKBNK.IS';
UPDATE public.stocks SET name = 'Akçansa Çimento Sanayi ve Ticaret' WHERE symbol = 'AKCNS.IS';
UPDATE public.stocks SET name = 'Akenerji Elektrik Üretim' WHERE symbol = 'AKENR.IS';
UPDATE public.stocks SET name = 'Akfen İnşaat Turizm ve İşletmecilik' WHERE symbol = 'AKFIS.IS';
UPDATE public.stocks SET name = 'Akfen Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'AKFGY.IS';
UPDATE public.stocks SET name = 'Akfen Yenilenebilir Enerji' WHERE symbol = 'AKFYE.IS';
UPDATE public.stocks SET name = 'Aksigorta' WHERE symbol = 'AKGRT.IS';
UPDATE public.stocks SET name = 'Akın Hayvancılık' WHERE symbol = 'AKHAN.IS';
UPDATE public.stocks SET name = 'Akmerkez Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'AKMGY.IS';
UPDATE public.stocks SET name = 'Aksa Akrilik Kimya Sanayii' WHERE symbol = 'AKSA.IS';
UPDATE public.stocks SET name = 'Aksa Enerji Üretim' WHERE symbol = 'AKSEN.IS';
UPDATE public.stocks SET name = 'Aksu Enerji ve Ticaret' WHERE symbol = 'AKSUE.IS';
UPDATE public.stocks SET name = 'Aksigorta' WHERE symbol = 'AKSYG.IS';
UPDATE public.stocks SET name = 'Akdeniz Yatırım Holding' WHERE symbol = 'AKYHO.IS';
UPDATE public.stocks SET name = 'Alarko Holding' WHERE symbol = 'ALARK.IS';
UPDATE public.stocks SET name = 'Albaraka Türk Katılım Bankası' WHERE symbol = 'ALBRK.IS';
UPDATE public.stocks SET name = 'Alarko Carrier Sanayi ve Ticaret' WHERE symbol = 'ALCAR.IS';
UPDATE public.stocks SET name = 'Alcatel Lucent Teletaş Telekomünikasyon' WHERE symbol = 'ALCTL.IS';
UPDATE public.stocks SET name = 'Alfa Solar Enerji Sanayi ve Ticaret' WHERE symbol = 'ALFAS.IS';
UPDATE public.stocks SET name = 'Alarko Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'ALGYO.IS';
UPDATE public.stocks SET name = 'Alka Sanayi Kağıt' WHERE symbol = 'ALKA.IS';
UPDATE public.stocks SET name = 'Alkim Alkali Kimya' WHERE symbol = 'ALKIM.IS';
UPDATE public.stocks SET name = 'Alkazar Teknoloji' WHERE symbol = 'ALKLC.IS';
UPDATE public.stocks SET name = 'Altınyağ Madencilik ve Enerji Yatırımları' WHERE symbol = 'ALMAD.IS';
UPDATE public.stocks SET name = 'Darphane Altın Sertifikası' WHERE symbol = 'ALTIN.IS';
UPDATE public.stocks SET name = 'Altınay Savunma Teknolojileri' WHERE symbol = 'ALTNY.IS';
UPDATE public.stocks SET name = 'Alves Kablo Sanayi ve Ticaret' WHERE symbol = 'ALVES.IS';
UPDATE public.stocks SET name = 'Anel Elektrik Proje Taahhüt ve Ticaret' WHERE symbol = 'ANELE.IS';
UPDATE public.stocks SET name = 'Anatolia Tanı ve Biyoteknoloji Ürünleri' WHERE symbol = 'ANGEN.IS';
UPDATE public.stocks SET name = 'Anadolu Hayat Emeklilik' WHERE symbol = 'ANHYT.IS';
UPDATE public.stocks SET name = 'Anadolu Sigorta' WHERE symbol = 'ANSGR.IS';
UPDATE public.stocks SET name = 'Doğu Aras Enerji Yatırımları' WHERE symbol = 'ARASE.IS';
UPDATE public.stocks SET name = 'Arçelik A.Ş.' WHERE symbol = 'ARCLK.IS';
UPDATE public.stocks SET name = 'ARD Grup Bilişim Teknolojileri' WHERE symbol = 'ARDYZ.IS';
UPDATE public.stocks SET name = 'Arena Bilgisayar Sanayi ve Ticaret' WHERE symbol = 'ARENA.IS';
UPDATE public.stocks SET name = 'Arf Finansal Yatırımlar' WHERE symbol = 'ARFYE.IS';
UPDATE public.stocks SET name = 'Armada Gıda Ticaret Sanayi' WHERE symbol = 'ARMGD.IS';
UPDATE public.stocks SET name = 'Arsan Tekstil Ticaret ve Sanayi' WHERE symbol = 'ARSAN.IS';
UPDATE public.stocks SET name = 'Artemis Halı' WHERE symbol = 'ARTMS.IS';
UPDATE public.stocks SET name = 'Arzum Elektrikli Ev Aletleri' WHERE symbol = 'ARZUM.IS';
UPDATE public.stocks SET name = 'Aselsan Elektronik Sanayi ve Ticaret' WHERE symbol = 'ASELS.IS';
UPDATE public.stocks SET name = 'Asce Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'ASGYO.IS';
UPDATE public.stocks SET name = 'Astor Enerji' WHERE symbol = 'ASTOR.IS';
UPDATE public.stocks SET name = 'Anadolu Isuzu Otomotiv Sanayi' WHERE symbol = 'ASUZU.IS';
UPDATE public.stocks SET name = 'Ata Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'ATAGY.IS';
UPDATE public.stocks SET name = 'Atakey Patates Gıda Sanayi' WHERE symbol = 'ATAKP.IS';
UPDATE public.stocks SET name = 'ATP Yazılım ve Teknoloji' WHERE symbol = 'ATATP.IS';
UPDATE public.stocks SET name = 'Ata Gayrimenkul' WHERE symbol = 'ATATR.IS';
UPDATE public.stocks SET name = 'Akın Tekstil' WHERE symbol = 'ATEK.IS';
UPDATE public.stocks SET name = 'Akın Tekstil' WHERE symbol = 'ATEKS.IS';
UPDATE public.stocks SET name = 'Atlas Menkul Kıymetler Yatırım Ortaklığı' WHERE symbol = 'ATLAS.IS';
UPDATE public.stocks SET name = 'Atlantis Yatırım Holding' WHERE symbol = 'ATSYH.IS';
UPDATE public.stocks SET name = 'Avrasya Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'AVGYO.IS';
UPDATE public.stocks SET name = 'Avrupa Yatırım Holding' WHERE symbol = 'AVHOL.IS';
UPDATE public.stocks SET name = 'A.V.O.D. Kurutulmuş Gıda ve Tarım Ürünleri' WHERE symbol = 'AVOD.IS';
UPDATE public.stocks SET name = 'Avrasya Petrol ve Turistik Tesisler' WHERE symbol = 'AVTUR.IS';
UPDATE public.stocks SET name = 'Altın Yunus Çeşme Turistik Tesisler' WHERE symbol = 'AYCES.IS';
UPDATE public.stocks SET name = 'Aydem Yenilenebilir Enerji' WHERE symbol = 'AYDEM.IS';
UPDATE public.stocks SET name = 'Ayen Enerji' WHERE symbol = 'AYEN.IS';
UPDATE public.stocks SET name = 'Ayes Çelik Hasır ve Çit Sanayi' WHERE symbol = 'AYES.IS';
UPDATE public.stocks SET name = 'Aygaz A.Ş.' WHERE symbol = 'AYGAZ.IS';
UPDATE public.stocks SET name = 'Aztek Teknoloji Ürünleri Ticaret' WHERE symbol = 'AZTEK.IS';
UPDATE public.stocks SET name = 'Bağfaş Bandırma Gübre Fabrikaları' WHERE symbol = 'BAGFS.IS';
UPDATE public.stocks SET name = 'Bahadır Kimya Sanayi ve Ticaret' WHERE symbol = 'BAHKM.IS';
UPDATE public.stocks SET name = 'Bak Ambalaj Sanayi ve Ticaret' WHERE symbol = 'BAKAB.IS';
UPDATE public.stocks SET name = 'Balatacılar Balatacılık Sanayi' WHERE symbol = 'BALAT.IS';
UPDATE public.stocks SET name = 'Balsu Gıda Sanayi ve Ticaret' WHERE symbol = 'BALSU.IS';
UPDATE public.stocks SET name = 'Banvit Bandırma Vitaminli Yem Sanayii' WHERE symbol = 'BANVT.IS';
UPDATE public.stocks SET name = 'Barem Ambalaj Sanayi ve Ticaret' WHERE symbol = 'BARMA.IS';
UPDATE public.stocks SET name = 'Baştaş Başkent Çimento Sanayi' WHERE symbol = 'BASCM.IS';
UPDATE public.stocks SET name = 'Başkent Doğalgaz Dağıtım' WHERE symbol = 'BASGZ.IS';
UPDATE public.stocks SET name = 'Bayrak Ebt Taban Sanayi ve Ticaret' WHERE symbol = 'BAYRK.IS';
UPDATE public.stocks SET name = 'Batı Ege Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'BEGYO.IS';
UPDATE public.stocks SET name = 'Bera Holding' WHERE symbol = 'BERA.IS';
UPDATE public.stocks SET name = 'Besler Tekstil Sanayi' WHERE symbol = 'BESLR.IS';
UPDATE public.stocks SET name = 'Bestepe Finansal Hizmetler' WHERE symbol = 'BESTE.IS';
UPDATE public.stocks SET name = 'Beyaz Filo Oto Kiralama' WHERE symbol = 'BEYAZ.IS';
UPDATE public.stocks SET name = 'Bosch Fren Sistemleri Sanayi ve Ticaret' WHERE symbol = 'BFREN.IS';
UPDATE public.stocks SET name = 'Bien Yapı Ürünleri Sanayi Turizm' WHERE symbol = 'BIENP.IS';
UPDATE public.stocks SET name = 'Bien Yapı Ürünleri Sanayi Turizm' WHERE symbol = 'BIENY.IS';
UPDATE public.stocks SET name = 'Big Chefs (Büyük Şefler Gıda)' WHERE symbol = 'BIGCH.IS';
UPDATE public.stocks SET name = 'Bigen Biyoteknoloji' WHERE symbol = 'BIGEN.IS';
UPDATE public.stocks SET name = 'Big Teknoloji' WHERE symbol = 'BIGTK.IS';
UPDATE public.stocks SET name = 'BİM Birleşik Mağazalar' WHERE symbol = 'BIMAS.IS';
UPDATE public.stocks SET name = 'Bin Ulaşım ve Akıllı Şehir (BinBin)' WHERE symbol = 'BINBN.IS';
UPDATE public.stocks SET name = '1000 Yatırımlar Holding' WHERE symbol = 'BINHO.IS';
UPDATE public.stocks SET name = 'Biotrend Çevre ve Enerji Yatırımları' WHERE symbol = 'BIOEN.IS';
UPDATE public.stocks SET name = 'Bizim Toptan Satış Mağazaları' WHERE symbol = 'BIZIM.IS';
UPDATE public.stocks SET name = 'Beşiktaş Futbol Yatırımları Sanayi' WHERE symbol = 'BJKAS.IS';
UPDATE public.stocks SET name = 'Bilici Yatırım Sanayi ve Ticaret' WHERE symbol = 'BLCYT.IS';
UPDATE public.stocks SET name = 'Blume Gayrimenkul' WHERE symbol = 'BLUME.IS';
UPDATE public.stocks SET name = 'BMS Çelik Hasır Sanayi ve Ticaret' WHERE symbol = 'BMSCH.IS';
UPDATE public.stocks SET name = 'BMS Birleşik Metal Sanayi' WHERE symbol = 'BMSTL.IS';
UPDATE public.stocks SET name = 'Bantaş Bandırma Ambalaj Sanayi' WHERE symbol = 'BNTAS.IS';
UPDATE public.stocks SET name = 'Boğaziçi Beton Sanayi ve Ticaret' WHERE symbol = 'BOBET.IS';
UPDATE public.stocks SET name = 'Borlease Otomotiv' WHERE symbol = 'BORLS.IS';
UPDATE public.stocks SET name = 'Bor Şeker A.Ş.' WHERE symbol = 'BORSK.IS';
UPDATE public.stocks SET name = 'Bossa Ticaret ve Sanayi İşletmeleri' WHERE symbol = 'BOSSA.IS';
UPDATE public.stocks SET name = 'Brisa Bridgestone Sabancı Lastik Sanayi' WHERE symbol = 'BRISA.IS';
UPDATE public.stocks SET name = 'Birko Birleşik Koyunlulular Mensucat' WHERE symbol = 'BRKO.IS';
UPDATE public.stocks SET name = 'Berkosan Yalıtım ve Tecrit Maddeleri' WHERE symbol = 'BRKSN.IS';
UPDATE public.stocks SET name = 'Birikim Varlık Yönetim' WHERE symbol = 'BRKVY.IS';
UPDATE public.stocks SET name = 'Birleşim Mühendislik Isıtma Soğutma' WHERE symbol = 'BRLSM.IS';
UPDATE public.stocks SET name = 'Birlik Mensucat Ticaret ve Sanayi' WHERE symbol = 'BRMEN.IS';
UPDATE public.stocks SET name = 'Borusan Birleşik Boru Fabrikaları' WHERE symbol = 'BRSAN.IS';
UPDATE public.stocks SET name = 'Borusan Yatırım ve Pazarlama' WHERE symbol = 'BRYAT.IS';
UPDATE public.stocks SET name = 'Batısöke Söke Çimento Sanayii' WHERE symbol = 'BSOKE.IS';
UPDATE public.stocks SET name = 'Batıçim Batı Anadolu Çimento Sanayii' WHERE symbol = 'BTCIM.IS';
UPDATE public.stocks SET name = 'Bursa Çimento Fabrikası' WHERE symbol = 'BUCIM.IS';
UPDATE public.stocks SET name = 'Bulut Gayrimenkul' WHERE symbol = 'BULGS.IS';
UPDATE public.stocks SET name = 'Burçelik Bursa Çelik Döküm Sanayi' WHERE symbol = 'BURCE.IS';
UPDATE public.stocks SET name = 'Burçelik Vana Sanayi ve Ticaret' WHERE symbol = 'BURVA.IS';
UPDATE public.stocks SET name = 'Bülbüloğlu Vinç Sanayi' WHERE symbol = 'BVSAN.IS';
UPDATE public.stocks SET name = 'Baydöner Restoranları' WHERE symbol = 'BYDNR.IS';
UPDATE public.stocks SET name = 'Çan2 Termik A.Ş.' WHERE symbol = 'CANTE.IS';
UPDATE public.stocks SET name = 'Casa Emtia Petrol Kimyevi ve Türevleri' WHERE symbol = 'CASA.IS';
UPDATE public.stocks SET name = 'Çates Elektrik Üretim' WHERE symbol = 'CATES.IS';
UPDATE public.stocks SET name = 'Coca-Cola İçecek A.Ş.' WHERE symbol = 'CCOLA.IS';
UPDATE public.stocks SET name = 'Çelik Halat ve Tel Sanayii' WHERE symbol = 'CELHA.IS';
UPDATE public.stocks SET name = 'Çemaş Döküm Sanayi' WHERE symbol = 'CEMAS.IS';
UPDATE public.stocks SET name = 'Çemtaş Çelik Makina Sanayi ve Ticaret' WHERE symbol = 'CEMTS.IS';
UPDATE public.stocks SET name = 'Çemzy Gayrimenkul' WHERE symbol = 'CEMZY.IS';
UPDATE public.stocks SET name = 'CEO Event Medya' WHERE symbol = 'CEOEM.IS';
UPDATE public.stocks SET name = 'CG Cam Endüstrisi' WHERE symbol = 'CGCAM.IS';
UPDATE public.stocks SET name = 'Çimsa Çimento Sanayi ve Ticaret' WHERE symbol = 'CIMSA.IS';
UPDATE public.stocks SET name = 'Çelebi Hava Servisi' WHERE symbol = 'CLEBI.IS';
UPDATE public.stocks SET name = 'Çimbeton Hazırbeton ve Prefabrik' WHERE symbol = 'CMBTN.IS';
UPDATE public.stocks SET name = 'Çimentaş İzmir Çimento Fabrikası' WHERE symbol = 'CMENT.IS';
UPDATE public.stocks SET name = 'Consus Enerji İşletmeciliği' WHERE symbol = 'CONSE.IS';
UPDATE public.stocks SET name = 'Cosmos Yatırım Holding' WHERE symbol = 'COSMO.IS';
UPDATE public.stocks SET name = 'Creditwest Faktoring' WHERE symbol = 'CRDFA.IS';
UPDATE public.stocks SET name = 'CarrefourSA Sabancı Ticaret Merkezi' WHERE symbol = 'CRFSA.IS';
UPDATE public.stocks SET name = 'Çuhadaroğlu Metal Sanayi ve Pazarlama' WHERE symbol = 'CUSAN.IS';
UPDATE public.stocks SET name = 'CVK Maden İşletmeleri Sanayi ve Ticaret' WHERE symbol = 'CVKMD.IS';
UPDATE public.stocks SET name = 'CW Enerji Mühendislik Ticaret ve Sanayi' WHERE symbol = 'CWENE.IS';
UPDATE public.stocks SET name = 'Dagi Yatırım Holding' WHERE symbol = 'DAGHL.IS';
UPDATE public.stocks SET name = 'Dagi Giyim Sanayi ve Ticaret' WHERE symbol = 'DAGI.IS';
UPDATE public.stocks SET name = 'Dap Gayrimenkul Geliştirme' WHERE symbol = 'DAPGM.IS';
UPDATE public.stocks SET name = 'Dardanel Önentaş Gıda Sanayi' WHERE symbol = 'DARDL.IS';
UPDATE public.stocks SET name = 'DCT Trading Dış Ticaret' WHERE symbol = 'DCTTR.IS';
UPDATE public.stocks SET name = 'Denge Yatırım Holding' WHERE symbol = 'DENGE.IS';
UPDATE public.stocks SET name = 'Derlüks Yatırım Holding' WHERE symbol = 'DERHL.IS';
UPDATE public.stocks SET name = 'Derimod Konfeksiyon Ayakkabı Deri Sanayi' WHERE symbol = 'DERIM.IS';
UPDATE public.stocks SET name = 'Desa Deri Sanayi ve Ticaret' WHERE symbol = 'DESA.IS';
UPDATE public.stocks SET name = 'Despec Bilgisayar Pazarlama ve Ticaret' WHERE symbol = 'DESPC.IS';
UPDATE public.stocks SET name = 'Deva Holding' WHERE symbol = 'DEVA.IS';
UPDATE public.stocks SET name = 'Datagate Bilgisayar Malzemeleri Ticaret' WHERE symbol = 'DGATE.IS';
UPDATE public.stocks SET name = 'Doğuş Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'DGGYO.IS';
UPDATE public.stocks SET name = 'Doğanlar Mobilya Grubu İmalat Sanayi' WHERE symbol = 'DGNMO.IS';
UPDATE public.stocks SET name = 'Ditaş Doğan Yedek Parça İmalat' WHERE symbol = 'DIRIT.IS';
UPDATE public.stocks SET name = 'Ditaş Doğan Yedek Parça İmalat' WHERE symbol = 'DITAS.IS';
UPDATE public.stocks SET name = 'Damla Kent Gayrimenkul' WHERE symbol = 'DMLKT.IS';
UPDATE public.stocks SET name = 'DMR Unlu Mamuller (Simit Sarayı)' WHERE symbol = 'DMRGD.IS';
UPDATE public.stocks SET name = 'Demisaş Döküm Emaye Mamulleri Sanayi' WHERE symbol = 'DMSAS.IS';
UPDATE public.stocks SET name = 'Dinamik Isı Makina Yalıtım Malzemeleri' WHERE symbol = 'DNISI.IS';
UPDATE public.stocks SET name = 'Doğuş Otomotiv Servis ve Ticaret' WHERE symbol = 'DOAS.IS';
UPDATE public.stocks SET name = 'Dofer Yapı Malzemeleri Sanayi ve Ticaret' WHERE symbol = 'DOFER.IS';
UPDATE public.stocks SET name = 'Dofer B Sanayi' WHERE symbol = 'DOFRB.IS';
UPDATE public.stocks SET name = 'DO & CO AG' WHERE symbol = 'DOCO.IS';
UPDATE public.stocks SET name = 'Doğusan Boru Sanayi ve Ticaret' WHERE symbol = 'DOGUB.IS';
UPDATE public.stocks SET name = 'Doğan Şirketler Grubu Holding' WHERE symbol = 'DOHOL.IS';
UPDATE public.stocks SET name = 'Döktaş Dökümcülük Ticaret ve Sanayi' WHERE symbol = 'DOKTA.IS';
UPDATE public.stocks SET name = 'Destek Finans Faktoring' WHERE symbol = 'DSTKF.IS';
UPDATE public.stocks SET name = 'Dünya Holding' WHERE symbol = 'DUNYH.IS';
UPDATE public.stocks SET name = 'Duran Doğan Basım ve Ambalaj Sanayi' WHERE symbol = 'DURDO.IS';
UPDATE public.stocks SET name = 'Durukan Şekerleme Sanayi ve Ticaret' WHERE symbol = 'DURKN.IS';
UPDATE public.stocks SET name = 'Dyo Boya Fabrikaları Sanayi ve Ticaret' WHERE symbol = 'DYOBY.IS';
UPDATE public.stocks SET name = 'Deniz Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'DZGYO.IS';
UPDATE public.stocks SET name = 'Ebebek Mağazacılık' WHERE symbol = 'EBEBK.IS';
UPDATE public.stocks SET name = 'Eczacıbaşı İlaç Sınai ve Finansal Yatırımlar' WHERE symbol = 'ECILC.IS';
UPDATE public.stocks SET name = 'Eco Gayrimenkul' WHERE symbol = 'ECOGR.IS';
UPDATE public.stocks SET name = 'Eczacıbaşı Yatırım Holding Ortaklığı' WHERE symbol = 'ECZYT.IS';
UPDATE public.stocks SET name = 'E-Data Teknoloji Geliştirme' WHERE symbol = 'EDATA.IS';
UPDATE public.stocks SET name = 'Edip Gayrimenkul Yatırım Sanayi ve Ticaret' WHERE symbol = 'EDIP.IS';
UPDATE public.stocks SET name = 'Efor Çay Sanayi Ticaret' WHERE symbol = 'EFOR.IS';
UPDATE public.stocks SET name = 'Ege Endüstri ve Ticaret' WHERE symbol = 'EGEEN.IS';
UPDATE public.stocks SET name = 'Ege Gayrimenkul' WHERE symbol = 'EGEGY.IS';
UPDATE public.stocks SET name = 'Nasmed Egepol Sağlık Hizmetleri' WHERE symbol = 'EGEPO.IS';
UPDATE public.stocks SET name = 'Ege Gübre Sanayii' WHERE symbol = 'EGGUB.IS';
UPDATE public.stocks SET name = 'Ege Profil Ticaret ve Sanayi' WHERE symbol = 'EGPRO.IS';
UPDATE public.stocks SET name = 'Ege Seramik Sanayi ve Ticaret' WHERE symbol = 'EGSER.IS';
UPDATE public.stocks SET name = 'Ekiz Kimya Sanayi ve Ticaret' WHERE symbol = 'EKIZ.IS';
UPDATE public.stocks SET name = 'Emlak Konut Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'EKGYO.IS';
UPDATE public.stocks SET name = 'Ekos Teknoloji ve Elektrik' WHERE symbol = 'EKOS.IS';
UPDATE public.stocks SET name = 'Eksun Gıda Tarım Sanayi ve Ticaret' WHERE symbol = 'EKSUN.IS';
UPDATE public.stocks SET name = 'Elite Naturel Organik Gıda Sanayi' WHERE symbol = 'ELITE.IS';
UPDATE public.stocks SET name = 'Emek Elektrik Endüstrisi' WHERE symbol = 'EMKEL.IS';
UPDATE public.stocks SET name = 'Eminiş Ambalaj Sanayi ve Ticaret' WHERE symbol = 'EMNIS.IS';
UPDATE public.stocks SET name = 'Empa Elektronik Sanayi' WHERE symbol = 'EMPAE.IS';
UPDATE public.stocks SET name = 'Enda Enerji Holding' WHERE symbol = 'ENDAE.IS';
UPDATE public.stocks SET name = 'Enerya Enerji A.Ş.' WHERE symbol = 'ENERY.IS';
UPDATE public.stocks SET name = 'Enerjisa Enerji A.Ş.' WHERE symbol = 'ENJSA.IS';
UPDATE public.stocks SET name = 'Enka İnşaat ve Sanayi' WHERE symbol = 'ENKAI.IS';
UPDATE public.stocks SET name = 'Ensari Deri Gıda Sanayi ve Ticaret' WHERE symbol = 'ENSRI.IS';
UPDATE public.stocks SET name = 'IC Enterra Yenilenebilir Enerji' WHERE symbol = 'ENTRA.IS';
UPDATE public.stocks SET name = 'Egeplast Ege Plastik Ticaret ve Sanayi' WHERE symbol = 'EPLAS.IS';
UPDATE public.stocks SET name = 'Erbosan Erciyas Boru Sanayii ve Ticaret' WHERE symbol = 'ERBOS.IS';
UPDATE public.stocks SET name = 'Erciyas Çelik Boru Sanayi' WHERE symbol = 'ERCB.IS';
UPDATE public.stocks SET name = 'Ereğli Demir ve Çelik Fabrikaları' WHERE symbol = 'EREGL.IS';
UPDATE public.stocks SET name = 'Ersu Meyve Suları Sarmaşık Konserve' WHERE symbol = 'ERSU.IS';
UPDATE public.stocks SET name = 'Escar Turizm Taşımacılık Ticaret' WHERE symbol = 'ESCAR.IS';
UPDATE public.stocks SET name = 'Escort Teknoloji Yatırım' WHERE symbol = 'ESCOM.IS';
UPDATE public.stocks SET name = 'Esenboğa Elektrik Üretim' WHERE symbol = 'ESEN.IS';
UPDATE public.stocks SET name = 'Etiler Gıda ve Ticari Yatırımlar' WHERE symbol = 'ETILR.IS';
UPDATE public.stocks SET name = 'Euro Trend Yatırım Ortaklığı' WHERE symbol = 'ETYAT.IS';
UPDATE public.stocks SET name = 'Euro Yatırım Holding' WHERE symbol = 'EUHOL.IS';
UPDATE public.stocks SET name = 'Euro Menkul Kıymetler Yatırım Ortaklığı' WHERE symbol = 'EUKYO.IS';
UPDATE public.stocks SET name = 'Europower Enerji ve Otomasyon Teknolojileri' WHERE symbol = 'EUPWR.IS';
UPDATE public.stocks SET name = 'Europen Endüstri Sanayi ve Ticaret' WHERE symbol = 'EUREN.IS';
UPDATE public.stocks SET name = 'Euro Yatırım Ortaklığı' WHERE symbol = 'EUYO.IS';
UPDATE public.stocks SET name = 'EYG Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'EYGYO.IS';
UPDATE public.stocks SET name = 'Fade Gıda Yatırım Sanayi ve Ticaret' WHERE symbol = 'FADE.IS';
UPDATE public.stocks SET name = 'Fenerbahçe Futbol A.Ş.' WHERE symbol = 'FENER.IS';
UPDATE public.stocks SET name = 'Flap Kongre Toplantı Hizmetleri Otomotiv ve Turizm' WHERE symbol = 'FLAP.IS';
UPDATE public.stocks SET name = 'Federal-Mogul İzmit Piston ve Pim Üretim' WHERE symbol = 'FMIZP.IS';
UPDATE public.stocks SET name = 'Fonet Bilgi Teknolojileri' WHERE symbol = 'FONET.IS';
UPDATE public.stocks SET name = 'Formet Metal ve Cam Sanayi' WHERE symbol = 'FORMT.IS';
UPDATE public.stocks SET name = 'Forte Bilgi İletişim Teknolojileri ve Savunma' WHERE symbol = 'FORTE.IS';
UPDATE public.stocks SET name = 'Frigo-Pak Gıda Maddeleri Sanayi ve Ticaret' WHERE symbol = 'FRIGO.IS';
UPDATE public.stocks SET name = 'Form Plastik Sanayi' WHERE symbol = 'FRMPL.IS';
UPDATE public.stocks SET name = 'Ford Otomotiv Sanayi A.Ş.' WHERE symbol = 'FROTO.IS';
UPDATE public.stocks SET name = 'Fuzul Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'FZLGY.IS';
UPDATE public.stocks SET name = 'Türkiye Garanti Bankası (Garanti BBVA)' WHERE symbol = 'GARAN.IS';
UPDATE public.stocks SET name = 'Garanti Faktoring' WHERE symbol = 'GARFA.IS';
UPDATE public.stocks SET name = 'Gateks İplik Sanayi' WHERE symbol = 'GATEG.IS';
UPDATE public.stocks SET name = 'Gür-Sel Turizm Yatırım' WHERE symbol = 'GBYAS.IS';
UPDATE public.stocks SET name = 'Gedik Yatırım Menkul Değerler' WHERE symbol = 'GEDIK.IS';
UPDATE public.stocks SET name = 'Gediz Ambalaj Sanayi ve Ticaret' WHERE symbol = 'GEDZA.IS';
UPDATE public.stocks SET name = 'Gen İlaç ve Sağlık Ürünleri Sanayi' WHERE symbol = 'GENIL.IS';
UPDATE public.stocks SET name = 'Genkim Kimya Sanayi' WHERE symbol = 'GENKM.IS';
UPDATE public.stocks SET name = 'Gentaş Dekoratif Yüzeyler Sanayi ve Ticaret' WHERE symbol = 'GENTS.IS';
UPDATE public.stocks SET name = 'Gersan Elektrik Ticaret ve Sanayi' WHERE symbol = 'GEREL.IS';
UPDATE public.stocks SET name = 'Girişim Elektrik Sanayi Taahhüt ve Ticaret' WHERE symbol = 'GESAN.IS';
UPDATE public.stocks SET name = 'Gıpta Ofis Kırtasiye ve Promosyon Ürünleri' WHERE symbol = 'GIPTA.IS';
UPDATE public.stocks SET name = 'Global Menkul Değerler' WHERE symbol = 'GLBMD.IS';
UPDATE public.stocks SET name = 'Gelecek Varlık Yönetimi' WHERE symbol = 'GLCVY.IS';
UPDATE public.stocks SET name = 'Gülermak Ağır Sanayi İnşaat' WHERE symbol = 'GLRMK.IS';
UPDATE public.stocks SET name = 'Güler Yatırım Holding' WHERE symbol = 'GLRYH.IS';
UPDATE public.stocks SET name = 'Global Yatırım Holding' WHERE symbol = 'GLYHO.IS';
UPDATE public.stocks SET name = 'Gimat Mağazacılık Sanayi ve Ticaret' WHERE symbol = 'GMTAS.IS';
UPDATE public.stocks SET name = 'Göknur Gıda Maddeleri Enerji İmalat' WHERE symbol = 'GOKNR.IS';
UPDATE public.stocks SET name = 'Göltaş Göller Bölgesi Çimento Sanayi' WHERE symbol = 'GOLTS.IS';
UPDATE public.stocks SET name = 'Good-Year Lastikleri Türk A.Ş.' WHERE symbol = 'GOODY.IS';
UPDATE public.stocks SET name = 'Gözde Girişim Sermayesi Yatırım Ortaklığı' WHERE symbol = 'GOZDE.IS';
UPDATE public.stocks SET name = 'Garanti Yatırım Ortaklığı' WHERE symbol = 'GRNYO.IS';
UPDATE public.stocks SET name = 'Gürsel Turizm Taşımacılık ve Servis' WHERE symbol = 'GRSEL.IS';
UPDATE public.stocks SET name = 'Güriş Holding' WHERE symbol = 'GRTHO.IS';
UPDATE public.stocks SET name = 'GSD Denizcilik Gayrimenkul İnşaat Sanayi' WHERE symbol = 'GSDDE.IS';
UPDATE public.stocks SET name = 'GSD Holding' WHERE symbol = 'GSDHO.IS';
UPDATE public.stocks SET name = 'Galatasaray Sportif Sınai ve Ticari Yatırımlar' WHERE symbol = 'GSRAY.IS';
UPDATE public.stocks SET name = 'Gübre Fabrikaları T.A.Ş.' WHERE symbol = 'GUBRF.IS';
UPDATE public.stocks SET name = 'Gündoğdu Gıda Süt Ürünleri Sanayi' WHERE symbol = 'GUNDG.IS';
UPDATE public.stocks SET name = 'Galata Wind Enerji A.Ş.' WHERE symbol = 'GWIND.IS';
UPDATE public.stocks SET name = 'Gezinomi Seyahat Turizm Finansal Hizmetler' WHERE symbol = 'GZNMI.IS';
UPDATE public.stocks SET name = 'Türkiye Halk Bankası A.Ş.' WHERE symbol = 'HALKB.IS';
UPDATE public.stocks SET name = 'Hateks Hatay Tekstil İşletmeleri' WHERE symbol = 'HATEK.IS';
UPDATE public.stocks SET name = 'Hatsan Gemi İnşaa Bakım Onarım Deniz Nakliyat' WHERE symbol = 'HATSN.IS';
UPDATE public.stocks SET name = 'Hedef Girişim Sermayesi Yatırım Ortaklığı' WHERE symbol = 'HDFGS.IS';
UPDATE public.stocks SET name = 'Hedef Holding' WHERE symbol = 'HEDEF.IS';
UPDATE public.stocks SET name = 'Hektaş Ticaret T.A.Ş.' WHERE symbol = 'HEKTS.IS';
UPDATE public.stocks SET name = 'Hidropar Hareket Kontrol Teknolojileri' WHERE symbol = 'HKTM.IS';
UPDATE public.stocks SET name = 'Halk Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'HLGYO.IS';
UPDATE public.stocks SET name = 'Horoz Lojistik Kargo Hizmetleri' WHERE symbol = 'HOROZ.IS';
UPDATE public.stocks SET name = 'Hareket Proje Taşımacılığı ve Yük Mühendisliği' WHERE symbol = 'HRKET.IS';
UPDATE public.stocks SET name = 'Hitit Bilgisayar Hizmetleri' WHERE symbol = 'HTTBT.IS';
UPDATE public.stocks SET name = 'Hub Girişim Sermayesi Yatırım Ortaklığı' WHERE symbol = 'HUBVC.IS';
UPDATE public.stocks SET name = 'Hun Yenilenebilir Enerji Üretim' WHERE symbol = 'HUNER.IS';
UPDATE public.stocks SET name = 'Hürriyet Gazetecilik ve Matbaacılık' WHERE symbol = 'HURGZ.IS';
UPDATE public.stocks SET name = 'ICBC Turkey Bank A.Ş.' WHERE symbol = 'ICBCT.IS';
UPDATE public.stocks SET name = 'İcu Girişim Sermayesi Yatırım Ortaklığı' WHERE symbol = 'ICUGS.IS';
UPDATE public.stocks SET name = 'İdealist Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'IDGYO.IS';
UPDATE public.stocks SET name = 'Işıklar Enerji ve Yapı Holding' WHERE symbol = 'IEYHO.IS';
UPDATE public.stocks SET name = 'İhlas Haber Ajansı' WHERE symbol = 'IHAAS.IS';
UPDATE public.stocks SET name = 'İhlas Ev Aletleri İmalat Sanayi ve Ticaret' WHERE symbol = 'IHEVA.IS';
UPDATE public.stocks SET name = 'İhlas Gazetecilik' WHERE symbol = 'IHGZT.IS';
UPDATE public.stocks SET name = 'İhlas Holding' WHERE symbol = 'IHLAS.IS';
UPDATE public.stocks SET name = 'İhlas Gayrimenkul Proje Geliştirme' WHERE symbol = 'IHLGM.IS';
UPDATE public.stocks SET name = 'İhlas Yayın Holding' WHERE symbol = 'IHYAY.IS';
UPDATE public.stocks SET name = 'İmaş Makina Sanayi' WHERE symbol = 'IMASM.IS';
UPDATE public.stocks SET name = 'İndeks Bilgisayar Sistemleri Mühendislik' WHERE symbol = 'INDES.IS';
UPDATE public.stocks SET name = 'İnfo Yatırım Menkul Değerler' WHERE symbol = 'INFO.IS';
UPDATE public.stocks SET name = 'Ingram Micro Bilişim Sistemleri' WHERE symbol = 'INGRM.IS';
UPDATE public.stocks SET name = 'İntek Bilişim ve Teknoloji' WHERE symbol = 'INTEK.IS';
UPDATE public.stocks SET name = 'İntema İnşaat ve Tesisat Malzemeleri Yatırım' WHERE symbol = 'INTEM.IS';
UPDATE public.stocks SET name = 'Inveo Yatırım Holding' WHERE symbol = 'INVEO.IS';
UPDATE public.stocks SET name = 'Investco Holding' WHERE symbol = 'INVES.IS';
UPDATE public.stocks SET name = 'İpek Doğal Enerji Kaynakları Araştırma' WHERE symbol = 'IPEKE.IS';
UPDATE public.stocks SET name = 'Türkiye İş Bankası (A)' WHERE symbol = 'ISATR.IS';
UPDATE public.stocks SET name = 'İşbir Holding' WHERE symbol = 'ISBIR.IS';
UPDATE public.stocks SET name = 'Türkiye İş Bankası (B)' WHERE symbol = 'ISBTR.IS';
UPDATE public.stocks SET name = 'Türkiye İş Bankası (C)' WHERE symbol = 'ISCTR.IS';
UPDATE public.stocks SET name = 'İskenderun Demir ve Çelik A.Ş.' WHERE symbol = 'ISDMR.IS';
UPDATE public.stocks SET name = 'İş Finansal Kiralama' WHERE symbol = 'ISFIN.IS';
UPDATE public.stocks SET name = 'İş Girişim Sermayesi Yatırım Ortaklığı' WHERE symbol = 'ISGSY.IS';
UPDATE public.stocks SET name = 'İş Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'ISGYO.IS';
UPDATE public.stocks SET name = 'Işık Plastik Sanayi ve Dış Ticaret Pazarlama' WHERE symbol = 'ISKPL.IS';
UPDATE public.stocks SET name = 'Türkiye İş Bankası (Kurucu)' WHERE symbol = 'ISKUR.IS';
UPDATE public.stocks SET name = 'İş Yatırım Menkul Değerler' WHERE symbol = 'ISMEN.IS';
UPDATE public.stocks SET name = 'İşbir Sentetik Dokuma Sanayi' WHERE symbol = 'ISSEN.IS';
UPDATE public.stocks SET name = 'İş Yatırım Ortaklığı' WHERE symbol = 'ISYAT.IS';
UPDATE public.stocks SET name = 'İzdemir Enerji Elektrik Üretim' WHERE symbol = 'IZENR.IS';
UPDATE public.stocks SET name = 'İzmir Fırça Sanayi ve Ticaret' WHERE symbol = 'IZFAS.IS';
UPDATE public.stocks SET name = 'İz Yatırım Holding' WHERE symbol = 'IZINV.IS';
UPDATE public.stocks SET name = 'İzmir Demir Çelik Sanayi' WHERE symbol = 'IZMDC.IS';
UPDATE public.stocks SET name = 'Jantsa Jant Sanayi ve Ticaret' WHERE symbol = 'JANTS.IS';
UPDATE public.stocks SET name = 'Kaplamin Ambalaj Sanayi ve Ticaret' WHERE symbol = 'KAPLM.IS';
UPDATE public.stocks SET name = 'Karel Elektronik Sanayi ve Ticaret' WHERE symbol = 'KAREL.IS';
UPDATE public.stocks SET name = 'Karsan Otomotiv Sanayii ve Ticaret' WHERE symbol = 'KARSN.IS';
UPDATE public.stocks SET name = 'Kartonsan Karton Sanayi ve Ticaret' WHERE symbol = 'KARTN.IS';
UPDATE public.stocks SET name = 'Kartal Yenilenebilir Enerji Üretim' WHERE symbol = 'KARYE.IS';
UPDATE public.stocks SET name = 'Katmerciler Araç Üstü Ekipman Sanayi' WHERE symbol = 'KATMR.IS';
UPDATE public.stocks SET name = 'Kayseri Şeker Fabrikası' WHERE symbol = 'KAYSE.IS';
UPDATE public.stocks SET name = 'Kuzey Boru A.Ş.' WHERE symbol = 'KBORU.IS';
UPDATE public.stocks SET name = 'Kocaer Çelik Sanayi ve Ticaret' WHERE symbol = 'KCAER.IS';
UPDATE public.stocks SET name = 'Koç Holding A.Ş.' WHERE symbol = 'KCHOL.IS';
UPDATE public.stocks SET name = 'Kent Gıda Maddeleri Sanayii ve Ticaret' WHERE symbol = 'KENT.IS';
UPDATE public.stocks SET name = 'Kervansaray Yatırım Holding' WHERE symbol = 'KERVN.IS';
UPDATE public.stocks SET name = 'Kerevitaş Gıda Sanayi ve Ticaret' WHERE symbol = 'KERVT.IS';
UPDATE public.stocks SET name = 'Kafein Yazılım Hizmetleri' WHERE symbol = 'KFEIN.IS';
UPDATE public.stocks SET name = 'Koray Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'KGYO.IS';
UPDATE public.stocks SET name = 'Ersan Alışveriş Hizmetleri (Kim Market)' WHERE symbol = 'KIMMR.IS';
UPDATE public.stocks SET name = 'Kalekim Kimyevi Maddeler Sanayi ve Ticaret' WHERE symbol = 'KLKIM.IS';
UPDATE public.stocks SET name = 'Klimasan Klima Sanayi ve Ticaret' WHERE symbol = 'KLMSN.IS';
UPDATE public.stocks SET name = 'Türkiye Kalkınma ve Yatırım Bankası' WHERE symbol = 'KLNMA.IS';
UPDATE public.stocks SET name = 'Kiler Holding' WHERE symbol = 'KLRHO.IS';
UPDATE public.stocks SET name = 'Kaleseramik Çanakkale Kalebodur Seramik Sanayi' WHERE symbol = 'KLSER.IS';
UPDATE public.stocks SET name = 'Koleksiyon Mobilya Sanayi ve Ticaret' WHERE symbol = 'KLSYN.IS';
UPDATE public.stocks SET name = 'Kalyon Güneş Teknolojileri' WHERE symbol = 'KLYAS.IS';
UPDATE public.stocks SET name = 'Kalyon Fotovoltaik Güneş Teknolojileri' WHERE symbol = 'KLYPV.IS';
UPDATE public.stocks SET name = 'Kimteks Poliüretan Sanayi ve Ticaret' WHERE symbol = 'KMPUR.IS';
UPDATE public.stocks SET name = 'Konfrut Tarım A.Ş.' WHERE symbol = 'KNFRT.IS';
UPDATE public.stocks SET name = 'Koç Metalurji' WHERE symbol = 'KOCMT.IS';
UPDATE public.stocks SET name = 'Konya Kağıt Sanayi ve Ticaret' WHERE symbol = 'KONKA.IS';
UPDATE public.stocks SET name = 'Kontrolmatik Teknoloji Enerji ve Mühendislik' WHERE symbol = 'KONTR.IS';
UPDATE public.stocks SET name = 'Konya Çimento Sanayii' WHERE symbol = 'KONYA.IS';
UPDATE public.stocks SET name = 'Koza Polyester Sanayi ve Ticaret' WHERE symbol = 'KOPOL.IS';
UPDATE public.stocks SET name = 'Kordsa Teknik Tekstil A.Ş.' WHERE symbol = 'KORDS.IS';
UPDATE public.stocks SET name = 'Koton Mağazacılık Tekstil Sanayi ve Ticaret' WHERE symbol = 'KOTON.IS';
UPDATE public.stocks SET name = 'Koza Anadolu Metal Madencilik İşletmeleri' WHERE symbol = 'KOZAA.IS';
UPDATE public.stocks SET name = 'Koza Altın İşletmeleri' WHERE symbol = 'KOZAL.IS';
UPDATE public.stocks SET name = 'Kardemir Karabük Demir Çelik (A)' WHERE symbol = 'KRDMA.IS';
UPDATE public.stocks SET name = 'Kardemir Karabük Demir Çelik (B)' WHERE symbol = 'KRDMB.IS';
UPDATE public.stocks SET name = 'Kardemir Karabük Demir Çelik (D)' WHERE symbol = 'KRDMD.IS';
UPDATE public.stocks SET name = 'Kron Telekomünikasyon Hizmetleri' WHERE symbol = 'KRONT.IS';
UPDATE public.stocks SET name = 'Koroplast Temizlik Ambalaj Ürünleri' WHERE symbol = 'KRPLS.IS';
UPDATE public.stocks SET name = 'Kristal Kola ve Meşrubat Sanayi' WHERE symbol = 'KRSTL.IS';
UPDATE public.stocks SET name = 'Karsu Tekstil Sanayii ve Ticaret' WHERE symbol = 'KRTEK.IS';
UPDATE public.stocks SET name = 'Kervan Gıda Sanayi ve Ticaret' WHERE symbol = 'KRVGD.IS';
UPDATE public.stocks SET name = 'Kuştur Kuşadası Turizm Endüstrisi' WHERE symbol = 'KSTUR.IS';
UPDATE public.stocks SET name = 'Katılımevim Tasarruf Finansman' WHERE symbol = 'KTLEV.IS';
UPDATE public.stocks SET name = 'Kütahya Şeker Fabrikası' WHERE symbol = 'KTSKR.IS';
UPDATE public.stocks SET name = 'Kütahya Porselen Sanayi' WHERE symbol = 'KUTPO.IS';
UPDATE public.stocks SET name = 'Kuvva Gıda Ticaret ve Yatırımlar' WHERE symbol = 'KUVVA.IS';
UPDATE public.stocks SET name = 'Kuyaş Yatırım A.Ş.' WHERE symbol = 'KUYAS.IS';
UPDATE public.stocks SET name = 'Kızılbük Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'KZBGY.IS';
UPDATE public.stocks SET name = 'Kuzugrup Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'KZGYO.IS';
UPDATE public.stocks SET name = 'Lider Faktoring' WHERE symbol = 'LIDER.IS';
UPDATE public.stocks SET name = 'Lider Faktoring' WHERE symbol = 'LIDFA.IS';
UPDATE public.stocks SET name = 'Lila Kağıt Sanayi ve Ticaret' WHERE symbol = 'LILAK.IS';
UPDATE public.stocks SET name = 'Link Bilgisayar Sistemleri Yazılımı' WHERE symbol = 'LINK.IS';
UPDATE public.stocks SET name = 'Lokman Hekim Engürüsağ Sağlık Turizm' WHERE symbol = 'LKMNH.IS';
UPDATE public.stocks SET name = 'Limak Doğu Anadolu Çimento Sanayi' WHERE symbol = 'LMKDC.IS';
UPDATE public.stocks SET name = 'Logo Siber Güvenlik' WHERE symbol = 'LOGAS.IS';
UPDATE public.stocks SET name = 'Logo Yazılım Sanayi ve Ticaret' WHERE symbol = 'LOGO.IS';
UPDATE public.stocks SET name = 'Larus Holding' WHERE symbol = 'LRSHL.IS';
UPDATE public.stocks SET name = 'Larus Holding' WHERE symbol = 'LRSHO.IS';
UPDATE public.stocks SET name = 'Lüks Kadife Ticaret ve Sanayii' WHERE symbol = 'LUKSK.IS';
UPDATE public.stocks SET name = 'Lux Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'LXGYO.IS';
UPDATE public.stocks SET name = 'Lydian Holding' WHERE symbol = 'LYDHO.IS';
UPDATE public.stocks SET name = 'Lydian Enerji' WHERE symbol = 'LYDYE.IS';
UPDATE public.stocks SET name = 'Marmaris Altınyunus Turistik Tesisleri' WHERE symbol = 'MAALT.IS';
UPDATE public.stocks SET name = 'Maçkolik İnternet Hizmetleri' WHERE symbol = 'MACKO.IS';
UPDATE public.stocks SET name = 'Margün Alternatif Enerji Üretim' WHERE symbol = 'MAGEN.IS';
UPDATE public.stocks SET name = 'Makim Makina Teknolojileri Sanayi' WHERE symbol = 'MAKIM.IS';
UPDATE public.stocks SET name = 'Makina Takım Endüstrisi' WHERE symbol = 'MAKTK.IS';
UPDATE public.stocks SET name = 'Manas Enerji Yönetimi Sanayi ve Ticaret' WHERE symbol = 'MANAS.IS';
UPDATE public.stocks SET name = 'Tureks Turunç Madencilik (Marble)' WHERE symbol = 'MARBL.IS';
UPDATE public.stocks SET name = 'Marka Yatırım Holding' WHERE symbol = 'MARKA.IS';
UPDATE public.stocks SET name = 'Marmara Çimento' WHERE symbol = 'MARMR.IS';
UPDATE public.stocks SET name = 'Martı Otel İşletmeleri' WHERE symbol = 'MARTI.IS';
UPDATE public.stocks SET name = 'Mavi Giyim Sanayi ve Ticaret' WHERE symbol = 'MAVI.IS';
UPDATE public.stocks SET name = 'Multi Kart Teknolojileri' WHERE symbol = 'MCARD.IS';
UPDATE public.stocks SET name = 'Medical Park (Tıbbi Tesisler Sağlık)' WHERE symbol = 'MEDTR.IS';
UPDATE public.stocks SET name = 'Mega Polietilen Köpük Sanayi ve Ticaret' WHERE symbol = 'MEGAP.IS';
UPDATE public.stocks SET name = 'Mega Metal Sanayi ve Ticaret' WHERE symbol = 'MEGMT.IS';
UPDATE public.stocks SET name = 'Meka Beton Santralleri İmalat Sanayi' WHERE symbol = 'MEKAG.IS';
UPDATE public.stocks SET name = 'Mepet Metro Petrol ve Tesisleri Sanayi' WHERE symbol = 'MEPET.IS';
UPDATE public.stocks SET name = 'Mercan Kimya Sanayi ve Ticaret' WHERE symbol = 'MERCN.IS';
UPDATE public.stocks SET name = 'Merit Turizm ve Yatırım İşletmeciliği' WHERE symbol = 'MERIT.IS';
UPDATE public.stocks SET name = 'Merko Gıda Sanayi ve Ticaret' WHERE symbol = 'MERKO.IS';
UPDATE public.stocks SET name = 'Metro Ticari ve Mali Yatırımlar Holding' WHERE symbol = 'METRO.IS';
UPDATE public.stocks SET name = 'Metemtur Otelcilik ve Turizm İşletmeleri' WHERE symbol = 'METUR.IS';
UPDATE public.stocks SET name = 'Meysu Gıda Sanayi ve Ticaret' WHERE symbol = 'MEYSU.IS';
UPDATE public.stocks SET name = 'Migros Ticaret A.Ş.' WHERE symbol = 'MGROS.IS';
UPDATE public.stocks SET name = 'MHR Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'MHRGY.IS';
UPDATE public.stocks SET name = 'Mia Teknoloji A.Ş.' WHERE symbol = 'MIATK.IS';
UPDATE public.stocks SET name = 'Milpa Ticari ve Sınai Ürünler Pazarlama' WHERE symbol = 'MIPAZ.IS';
UPDATE public.stocks SET name = 'MMC Sanayi ve Ticari Yatırımlar' WHERE symbol = 'MMCAS.IS';
UPDATE public.stocks SET name = 'Menderes Tekstil Sanayi ve Ticaret' WHERE symbol = 'MNDRS.IS';
UPDATE public.stocks SET name = 'Mondi Turkey Oluklu Mukavva Kağıt' WHERE symbol = 'MNDTR.IS';
UPDATE public.stocks SET name = 'Mobiltel İletişim Hizmetleri Sanayi' WHERE symbol = 'MOBTL.IS';
UPDATE public.stocks SET name = 'Mogan Enerji Yatırım Holding' WHERE symbol = 'MOGAN.IS';
UPDATE public.stocks SET name = 'Mopaş Marketçilik Gıda Sanayi' WHERE symbol = 'MOPAS.IS';
UPDATE public.stocks SET name = 'MLP Sağlık Hizmetleri (Medical Park)' WHERE symbol = 'MPARK.IS';
UPDATE public.stocks SET name = 'Martı Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'MRGYO.IS';
UPDATE public.stocks SET name = 'Marshall Boya ve Vernik Sanayii' WHERE symbol = 'MRSHL.IS';
UPDATE public.stocks SET name = 'Mistral Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'MSGYO.IS';
UPDATE public.stocks SET name = 'Matriks Bilgi Dağıtım Hizmetleri' WHERE symbol = 'MTRKS.IS';
UPDATE public.stocks SET name = 'Metro Yatırım Ortaklığı' WHERE symbol = 'MTRYO.IS';
UPDATE public.stocks SET name = 'Mazhar Zorlu Holding' WHERE symbol = 'MZHLD.IS';
UPDATE public.stocks SET name = 'Naturel Yenilenebilir Enerji Ticaret' WHERE symbol = 'NATEN.IS';
UPDATE public.stocks SET name = 'Netaş Telekomünikasyon' WHERE symbol = 'NETAS.IS';
UPDATE public.stocks SET name = 'Netcad Yazılım' WHERE symbol = 'NETCD.IS';
UPDATE public.stocks SET name = 'Niğbaş Niğde Beton Sanayi ve Ticaret' WHERE symbol = 'NIBAS.IS';
UPDATE public.stocks SET name = 'Naturelgaz Sanayi ve Ticaret' WHERE symbol = 'NTGAZ.IS';
UPDATE public.stocks SET name = 'Net Holding' WHERE symbol = 'NTHOL.IS';
UPDATE public.stocks SET name = 'Nurol Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'NUGYO.IS';
UPDATE public.stocks SET name = 'Nuh Çimento Sanayi' WHERE symbol = 'NUHCM.IS';
UPDATE public.stocks SET name = 'Oba Makarnacılık Sanayi ve Ticaret' WHERE symbol = 'OBAMS.IS';
UPDATE public.stocks SET name = 'Obase Bilgisayar ve Danışmanlık Hizmetleri' WHERE symbol = 'OBASE.IS';
UPDATE public.stocks SET name = 'Odaş Elektrik Üretim Sanayi Ticaret' WHERE symbol = 'ODAS.IS';
UPDATE public.stocks SET name = 'Odine Solutions Teknoloji Ticaret' WHERE symbol = 'ODINE.IS';
UPDATE public.stocks SET name = 'Ofis Yem Gıda Sanayi ve Ticaret' WHERE symbol = 'OFSYM.IS';
UPDATE public.stocks SET name = 'Oncosem Onkolojik Sistemler Sanayi' WHERE symbol = 'ONCSM.IS';
UPDATE public.stocks SET name = 'Onur Yüksek Teknoloji' WHERE symbol = 'ONRYT.IS';
UPDATE public.stocks SET name = 'Ortaköy Çay Sanayi ve Ticaret' WHERE symbol = 'ORCAY.IS';
UPDATE public.stocks SET name = 'Orge Enerji Elektrik Taahhüt' WHERE symbol = 'ORGE.IS';
UPDATE public.stocks SET name = 'Orma Orman Mahsulleri İntegre Sanayi' WHERE symbol = 'ORMA.IS';
UPDATE public.stocks SET name = 'Osmanlı Yatırım Menkul Değerler' WHERE symbol = 'OSMEN.IS';
UPDATE public.stocks SET name = 'Ostim Endüstriyel Yatırımlar ve İşletme' WHERE symbol = 'OSTIM.IS';
UPDATE public.stocks SET name = 'Otokar Otomotiv ve Savunma Sanayi' WHERE symbol = 'OTKAR.IS';
UPDATE public.stocks SET name = 'Otto Holding' WHERE symbol = 'OTTO.IS';
UPDATE public.stocks SET name = 'Oyak Çimento Fabrikaları' WHERE symbol = 'OYAKC.IS';
UPDATE public.stocks SET name = 'Oyak Yatırım Ortaklığı' WHERE symbol = 'OYAYO.IS';
UPDATE public.stocks SET name = 'Oylum Sınai Yatırımlar' WHERE symbol = 'OYLUM.IS';
UPDATE public.stocks SET name = 'Oyak Yatırım Menkul Değerler' WHERE symbol = 'OYYAT.IS';
UPDATE public.stocks SET name = 'Özata Denizcilik Sanayi ve Ticaret' WHERE symbol = 'OZATD.IS';
UPDATE public.stocks SET name = 'Özderici Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'OZGYO.IS';
UPDATE public.stocks SET name = 'Özak Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'OZKGY.IS';
UPDATE public.stocks SET name = 'Özerden Plastik Sanayi ve Ticaret' WHERE symbol = 'OZRDN.IS';
UPDATE public.stocks SET name = 'Özsu Balık Üretimi' WHERE symbol = 'OZSUB.IS';
UPDATE public.stocks SET name = 'Özyaşar Tel ve Çok Amaçlı Tel Sanayi' WHERE symbol = 'OZYSR.IS';
UPDATE public.stocks SET name = 'Panora Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'PAGYO.IS';
UPDATE public.stocks SET name = 'Pasifik Holding' WHERE symbol = 'PAHOL.IS';
UPDATE public.stocks SET name = 'Pamukova Elektrik Üretim' WHERE symbol = 'PAMEL.IS';
UPDATE public.stocks SET name = 'Papara Elektronik Para' WHERE symbol = 'PAPA.IS';
UPDATE public.stocks SET name = 'Papilon Savunma Güvenlik Sistemleri' WHERE symbol = 'PAPIL.IS';
UPDATE public.stocks SET name = 'Parsan Makina Parçaları Sanayii' WHERE symbol = 'PARSN.IS';
UPDATE public.stocks SET name = 'Pasifik Eurasia Lojistik Dış Ticaret' WHERE symbol = 'PASEU.IS';
UPDATE public.stocks SET name = 'Pasifik Donanım ve Yazılım Bilgi Teknolojileri' WHERE symbol = 'PATEK.IS';
UPDATE public.stocks SET name = 'Pc İletişim ve Medya Hizmetleri Sanayi' WHERE symbol = 'PCILT.IS';
UPDATE public.stocks SET name = 'Pera Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'PEGYO.IS';
UPDATE public.stocks SET name = 'Peker Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'PEKGY.IS';
UPDATE public.stocks SET name = 'Penguen Gıda Sanayi' WHERE symbol = 'PENGD.IS';
UPDATE public.stocks SET name = 'Penta Teknoloji Ürünleri Dağıtım' WHERE symbol = 'PENTA.IS';
UPDATE public.stocks SET name = 'Petkim Petrokimya Holding' WHERE symbol = 'PETKM.IS';
UPDATE public.stocks SET name = 'Pınar Entegre Et ve Un Sanayii' WHERE symbol = 'PETUN.IS';
UPDATE public.stocks SET name = 'Pegasus Hava Taşımacılığı' WHERE symbol = 'PGSUS.IS';
UPDATE public.stocks SET name = 'Pınar Su ve İçecek Sanayi' WHERE symbol = 'PINSU.IS';
UPDATE public.stocks SET name = 'Plastikkart Akıllı Kart İletişim Sistemleri' WHERE symbol = 'PKART.IS';
UPDATE public.stocks SET name = 'Petrokent Turizm' WHERE symbol = 'PKENT.IS';
UPDATE public.stocks SET name = 'Platform Turizm Taşımacılık' WHERE symbol = 'PLTUR.IS';
UPDATE public.stocks SET name = 'Panelsan Çatı Cephe Sistemleri Sanayi' WHERE symbol = 'PNLSN.IS';
UPDATE public.stocks SET name = 'Pınar Süt Mamülleri Sanayii' WHERE symbol = 'PNSUT.IS';
UPDATE public.stocks SET name = 'Polisan Holding' WHERE symbol = 'POLHO.IS';
UPDATE public.stocks SET name = 'Politeknik Metal Sanayi ve Ticaret' WHERE symbol = 'POLTK.IS';
UPDATE public.stocks SET name = 'Pardus Girişim Sermayesi Yatırım Ortaklığı' WHERE symbol = 'PRDGS.IS';
UPDATE public.stocks SET name = 'Türk Prysmian Kablo ve Sistemleri' WHERE symbol = 'PRKAB.IS';
UPDATE public.stocks SET name = 'Park Elektrik Üretim Madencilik Sanayi' WHERE symbol = 'PRKME.IS';
UPDATE public.stocks SET name = 'Prizma Pres Matbaacılık Yayıncılık' WHERE symbol = 'PRZMA.IS';
UPDATE public.stocks SET name = 'Pergamon Status Dış Ticaret' WHERE symbol = 'PSDTC.IS';
UPDATE public.stocks SET name = 'Pasifik Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'PSGYO.IS';
UPDATE public.stocks SET name = 'QNB Finans Finansal Kiralama' WHERE symbol = 'QNBFK.IS';
UPDATE public.stocks SET name = 'QNB Türkiye (QNB Finansbank)' WHERE symbol = 'QNBTR.IS';
UPDATE public.stocks SET name = 'Qua Granite Hayal Yapı ve Ürünleri' WHERE symbol = 'QUAGR.IS';
UPDATE public.stocks SET name = 'Ral Yatırım Holding' WHERE symbol = 'RALYH.IS';
UPDATE public.stocks SET name = 'Ray Sigorta' WHERE symbol = 'RAYSG.IS';
UPDATE public.stocks SET name = 'Ray Sigorta' WHERE symbol = 'RAYYS.IS';
UPDATE public.stocks SET name = 'Reeder Teknoloji Sanayi ve Ticaret' WHERE symbol = 'REEDR.IS';
UPDATE public.stocks SET name = 'Rönesans Gayrimenkul Yatırım' WHERE symbol = 'RGYAS.IS';
UPDATE public.stocks SET name = 'Rainbow Polikarbonat Sanayi ve Ticaret' WHERE symbol = 'RNPOL.IS';
UPDATE public.stocks SET name = 'Rodrigo Tekstil Sanayi ve Ticaret' WHERE symbol = 'RODRG.IS';
UPDATE public.stocks SET name = 'Royal Halı İplik Tekstil Mobilya' WHERE symbol = 'ROYAL.IS';
UPDATE public.stocks SET name = 'RTA Laboratuvarları Biyolojik Ürünler İlaç' WHERE symbol = 'RTALB.IS';
UPDATE public.stocks SET name = 'Rubenis Mensucat Sanayi ve Ticaret' WHERE symbol = 'RUBNS.IS';
UPDATE public.stocks SET name = 'Rüzgar Yenilenebilir Enerji' WHERE symbol = 'RUZYE.IS';
UPDATE public.stocks SET name = 'Reysaş Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'RYGYO.IS';
UPDATE public.stocks SET name = 'Reysaş Taşımacılık ve Lojistik Ticaret' WHERE symbol = 'RYSAS.IS';
UPDATE public.stocks SET name = 'Safkar Ege Soğutmacılık Klima Soğuk Hava' WHERE symbol = 'SAFKR.IS';
UPDATE public.stocks SET name = 'Hacı Ömer Sabancı Holding' WHERE symbol = 'SAHOL.IS';
UPDATE public.stocks SET name = 'Saray Matbaacılık Kağıtçılık Kırtasiyecilik' WHERE symbol = 'SAMAT.IS';
UPDATE public.stocks SET name = 'San-El Mühendislik Elektrik Taahhüt' WHERE symbol = 'SANEL.IS';
UPDATE public.stocks SET name = 'Sanifoam Sünger Sanayi ve Ticaret' WHERE symbol = 'SANFM.IS';
UPDATE public.stocks SET name = 'Sanko Pazarlama İthalat İhracat' WHERE symbol = 'SANKO.IS';
UPDATE public.stocks SET name = 'Sarkuysan Elektrolitik Bakır Sanayii' WHERE symbol = 'SARKY.IS';
UPDATE public.stocks SET name = 'SASA Polyester Sanayi' WHERE symbol = 'SASA.IS';
UPDATE public.stocks SET name = 'Say Yenilenebilir Enerji Ekipmanları Sanayi' WHERE symbol = 'SAYAS.IS';
UPDATE public.stocks SET name = 'SDT Uzay ve Savunma Teknolojileri' WHERE symbol = 'SDTTR.IS';
UPDATE public.stocks SET name = 'Seğmen Kardeşler Gıda Üretim' WHERE symbol = 'SEGMN.IS';
UPDATE public.stocks SET name = 'Şeker Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'SEGYO.IS';
UPDATE public.stocks SET name = 'Şeker Finansal Kiralama' WHERE symbol = 'SEKFK.IS';
UPDATE public.stocks SET name = 'Sekuro Plastik Ambalaj Sanayi' WHERE symbol = 'SEKUR.IS';
UPDATE public.stocks SET name = 'Selçuk Ecza Deposu Ticaret ve Sanayi' WHERE symbol = 'SELEC.IS';
UPDATE public.stocks SET name = 'Selçuk Gıda Endüstri İhracat İthalat' WHERE symbol = 'SELGD.IS';
UPDATE public.stocks SET name = 'Selva Gıda Sanayi' WHERE symbol = 'SELVA.IS';
UPDATE public.stocks SET name = 'Serenat Tekstil Sanayi' WHERE symbol = 'SERNT.IS';
UPDATE public.stocks SET name = 'Seyitler Kimya Sanayi' WHERE symbol = 'SEYKM.IS';
UPDATE public.stocks SET name = 'Silverline Endüstri ve Ticaret' WHERE symbol = 'SILVR.IS';
UPDATE public.stocks SET name = 'Türkiye Şişe ve Cam Fabrikaları' WHERE symbol = 'SISE.IS';
UPDATE public.stocks SET name = 'Şekerbank T.A.Ş.' WHERE symbol = 'SKBNK.IS';
UPDATE public.stocks SET name = 'Söktaş Tekstil Sanayi ve Ticaret' WHERE symbol = 'SKTAS.IS';
UPDATE public.stocks SET name = 'Sky Alp Havacılık' WHERE symbol = 'SKYLP.IS';
UPDATE public.stocks SET name = 'Şeker Yatırım Menkul Değerler' WHERE symbol = 'SKYMD.IS';
UPDATE public.stocks SET name = 'Smartiks Yazılım' WHERE symbol = 'SMART.IS';
UPDATE public.stocks SET name = 'Smart Güneş Enerjisi Teknolojileri' WHERE symbol = 'SMRTG.IS';
UPDATE public.stocks SET name = 'Sümer Varlık Yönetim' WHERE symbol = 'SMRVA.IS';
UPDATE public.stocks SET name = 'Sinpaş Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'SNGYO.IS';
UPDATE public.stocks SET name = 'Sanica Isı Sanayi' WHERE symbol = 'SNICA.IS';
UPDATE public.stocks SET name = 'Sanko Pazarlama' WHERE symbol = 'SNKPA.IS';
UPDATE public.stocks SET name = 'Sönmez Pamuklu Sanayii' WHERE symbol = 'SNPAM.IS';
UPDATE public.stocks SET name = 'Sodaş Sodyum Sanayii' WHERE symbol = 'SODSN.IS';
UPDATE public.stocks SET name = 'Söke Değirmencilik Sanayi ve Ticaret' WHERE symbol = 'SOKE.IS';
UPDATE public.stocks SET name = 'Şok Marketler Ticaret' WHERE symbol = 'SOKM.IS';
UPDATE public.stocks SET name = 'Sönmez Filament Sentetik İplik Sanayii' WHERE symbol = 'SONME.IS';
UPDATE public.stocks SET name = 'Servet Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'SRVGY.IS';
UPDATE public.stocks SET name = 'Sumaş Suni Tahta ve Mobilya Sanayi' WHERE symbol = 'SUMAS.IS';
UPDATE public.stocks SET name = 'Sun Tekstil Sanayi ve Ticaret' WHERE symbol = 'SUNTK.IS';
UPDATE public.stocks SET name = 'Sur Tatil Evleri Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'SURGY.IS';
UPDATE public.stocks SET name = 'Suwen Tekstil Sanayi ve Pazarlama' WHERE symbol = 'SUWEN.IS';
UPDATE public.stocks SET name = 'TAB Gıda Sanayi ve Ticaret' WHERE symbol = 'TABGD.IS';
UPDATE public.stocks SET name = 'Tarkim Bitki Koruma Sanayi ve Ticaret' WHERE symbol = 'TARKM.IS';
UPDATE public.stocks SET name = 'Tatlıpınar Enerji Üretim' WHERE symbol = 'TATEN.IS';
UPDATE public.stocks SET name = 'Tat Gıda Sanayi' WHERE symbol = 'TATGD.IS';
UPDATE public.stocks SET name = 'TAV Havalimanları Holding' WHERE symbol = 'TAVHL.IS';
UPDATE public.stocks SET name = 'Turkcell İletişim Hizmetleri' WHERE symbol = 'TCELL.IS';
UPDATE public.stocks SET name = 'Trend Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'TDGYO.IS';
UPDATE public.stocks SET name = 'Tek-Art İnşaat Ticaret Turizm Sanayi' WHERE symbol = 'TEKTU.IS';
UPDATE public.stocks SET name = 'Tera Yatırım Menkul Değerler' WHERE symbol = 'TERA.IS';
UPDATE public.stocks SET name = 'Tetamat Gıda Yatırımları' WHERE symbol = 'TETMT.IS';
UPDATE public.stocks SET name = 'TGS Dış Ticaret' WHERE symbol = 'TGSAS.IS';
UPDATE public.stocks SET name = 'Türk Hava Yolları A.O.' WHERE symbol = 'THYAO.IS';
UPDATE public.stocks SET name = 'Mondi Tire Kutsan Kağıt ve Ambalaj' WHERE symbol = 'TIRE.IS';
UPDATE public.stocks SET name = 'Tekfen Holding' WHERE symbol = 'TKFEN.IS';
UPDATE public.stocks SET name = 'Teknosa İç ve Dış Ticaret' WHERE symbol = 'TKNSA.IS';
UPDATE public.stocks SET name = 'Tilaş Lojistik' WHERE symbol = 'TLSAS.IS';
UPDATE public.stocks SET name = 'Temapol Polimer Plastik ve İnşaat Sanayi' WHERE symbol = 'TMPOL.IS';
UPDATE public.stocks SET name = 'Tümosan Motor ve Traktör Sanayi' WHERE symbol = 'TMSN.IS';
UPDATE public.stocks SET name = 'Tofaş Türk Otomobil Fabrikası' WHERE symbol = 'TOASO.IS';
UPDATE public.stocks SET name = 'Turcas Petrol' WHERE symbol = 'TRCAS.IS';
UPDATE public.stocks SET name = 'Torunlar Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'TRGYO.IS';
UPDATE public.stocks SET name = 'Türk İlaç ve Serum Sanayi' WHERE symbol = 'TRILC.IS';
UPDATE public.stocks SET name = 'Türkiye Sınai Kalkınma Bankası' WHERE symbol = 'TSKB.IS';
UPDATE public.stocks SET name = 'Trabzonspor Sportif Yatırım ve Ticaret' WHERE symbol = 'TSPOR.IS';
UPDATE public.stocks SET name = 'Türk Telekomünikasyon A.Ş.' WHERE symbol = 'TTKOM.IS';
UPDATE public.stocks SET name = 'Türk Traktör ve Ziraat Makineleri' WHERE symbol = 'TTRAK.IS';
UPDATE public.stocks SET name = 'Tuğçelik Alüminyum ve Metal Mamülleri' WHERE symbol = 'TUCLK.IS';
UPDATE public.stocks SET name = 'Tukaş Gıda Sanayi ve Ticaret' WHERE symbol = 'TUKAS.IS';
UPDATE public.stocks SET name = 'TÜPRAŞ - Türkiye Petrol Rafinerileri' WHERE symbol = 'TUPRS.IS';
UPDATE public.stocks SET name = 'Tureks Turizm Taşımacılık' WHERE symbol = 'TUREX.IS';
UPDATE public.stocks SET name = 'Türker Proje Gayrimenkul ve Yatırım' WHERE symbol = 'TURGG.IS';
UPDATE public.stocks SET name = 'Türkiye Sigorta A.Ş.' WHERE symbol = 'TURSG.IS';
UPDATE public.stocks SET name = 'Ufuk Yatırım Yönetim ve Gayrimenkul' WHERE symbol = 'UFUK.IS';
UPDATE public.stocks SET name = 'Ulaşlar Turizm Yatırımları ve Dayanıklı Tüketim' WHERE symbol = 'ULAS.IS';
UPDATE public.stocks SET name = 'Ülker Bisküvi Sanayi' WHERE symbol = 'ULKER.IS';
UPDATE public.stocks SET name = 'Ulusal Faktoring' WHERE symbol = 'ULUFA.IS';
UPDATE public.stocks SET name = 'Ulusoy Elektrik İmalat Taahhüt ve Ticaret' WHERE symbol = 'ULUSE.IS';
UPDATE public.stocks SET name = 'Ulusoy Un Sanayi ve Ticaret' WHERE symbol = 'ULUN.IS';
UPDATE public.stocks SET name = 'Umpaş Holding' WHERE symbol = 'UMPAS.IS';
UPDATE public.stocks SET name = 'Ünlü Yatırım Holding' WHERE symbol = 'UNLU.IS';
UPDATE public.stocks SET name = 'Uşak Seramik Sanayi' WHERE symbol = 'USAK.IS';
UPDATE public.stocks SET name = 'Türkiye Vakıflar Bankası (VakıfBank)' WHERE symbol = 'VAKBN.IS';
UPDATE public.stocks SET name = 'Vakıf Finansal Kiralama' WHERE symbol = 'VAKFN.IS';
UPDATE public.stocks SET name = 'Vakko Tekstil ve Hazır Giyim Sanayi' WHERE symbol = 'VAKKO.IS';
UPDATE public.stocks SET name = 'Vanet Gıda Sanayi İç ve Dış Ticaret' WHERE symbol = 'VANGD.IS';
UPDATE public.stocks SET name = 'VBT Yazılım A.Ş.' WHERE symbol = 'VBTYZ.IS';
UPDATE public.stocks SET name = 'Verusaturk Girişim Sermayesi Yatırım Ortaklığı' WHERE symbol = 'VERTU.IS';
UPDATE public.stocks SET name = 'Verusa Holding' WHERE symbol = 'VERUS.IS';
UPDATE public.stocks SET name = 'Vestel Beyaz Eşya Sanayi ve Ticaret' WHERE symbol = 'VESBE.IS';
UPDATE public.stocks SET name = 'Vestel Elektronik Sanayi ve Ticaret' WHERE symbol = 'VESTL.IS';
UPDATE public.stocks SET name = 'Vakıf Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'VKGYO.IS';
UPDATE public.stocks SET name = 'Viking Kağıt ve Selüloz' WHERE symbol = 'VKING.IS';
UPDATE public.stocks SET name = 'Yaprak Süt ve Besi Çiftlikleri Sanayi' WHERE symbol = 'YAPRK.IS';
UPDATE public.stocks SET name = 'Yataş Yatak ve Yorgan Sanayi ve Ticaret' WHERE symbol = 'YATAS.IS';
UPDATE public.stocks SET name = 'Yayla Enerji Üretim Turizm ve İnşaat' WHERE symbol = 'YAYLA.IS';
UPDATE public.stocks SET name = 'Yibitaş Yozgat İşçi Birliği İnşaat Malzemeleri' WHERE symbol = 'YBTAS.IS';
UPDATE public.stocks SET name = 'YEO Teknoloji Enerji ve Endüstri' WHERE symbol = 'YEOTK.IS';
UPDATE public.stocks SET name = 'Yeşil Yatırım Holding' WHERE symbol = 'YESIL.IS';
UPDATE public.stocks SET name = 'Yeni Gimat Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'YGGYO.IS';
UPDATE public.stocks SET name = 'Yeşil Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'YGYO.IS';
UPDATE public.stocks SET name = 'Yapı ve Kredi Bankası A.Ş.' WHERE symbol = 'YKBNK.IS';
UPDATE public.stocks SET name = 'Yükselen Çelik' WHERE symbol = 'YKSLN.IS';
UPDATE public.stocks SET name = 'Yonga Mobilya Sanayi ve Ticaret' WHERE symbol = 'YONGA.IS';
UPDATE public.stocks SET name = 'Yotaş Gayrimenkul' WHERE symbol = 'YOTAS.IS';
UPDATE public.stocks SET name = 'Yünsa Yünlü Sanayi ve Ticaret' WHERE symbol = 'YUNSA.IS';
UPDATE public.stocks SET name = 'Yeşil Yapı Endüstrisi' WHERE symbol = 'YYAPI.IS';
UPDATE public.stocks SET name = 'Yayla Agro Gıda Sanayi ve Ticaret' WHERE symbol = 'YYLGD.IS';
UPDATE public.stocks SET name = 'Zedur Enerji Elektrik Üretim' WHERE symbol = 'ZEDUR.IS';
UPDATE public.stocks SET name = 'Zorlu Enerji Elektrik Üretim' WHERE symbol = 'ZOREN.IS';
UPDATE public.stocks SET name = 'Ziraat Gayrimenkul Yatırım Ortaklığı' WHERE symbol = 'ZRGYO.IS';
