-- Create stocks table if it doesn't exist
-- Note: Java Spring Boot with Hibernate 'ddl-auto: update' creates this automatically.
-- This script is for manual verification and database initialization.

CREATE TABLE IF NOT EXISTS stocks (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(100),
    category VARCHAR(50),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Index for faster symbol lookups (used by Watchlist and Analysis)
CREATE INDEX IF NOT EXISTS idx_stocks_symbol ON stocks(symbol);

-- Populate stocks table with all BIST symbols
-- If symbols exist, it will skip them to avoid duplicates.
INSERT INTO stocks (symbol, name, category, is_active)
VALUES
('A1CAP.IS', 'A1CAP', 'BIST', true), ('ACSEL.IS', 'ACSEL', 'BIST', true), ('ADEL.IS', 'ADEL', 'BIST', true), ('ADESE.IS', 'ADESE', 'BIST', true), ('AEFES.IS', 'AEFES', 'BIST', true),
('AFYON.IS', 'AFYON', 'BIST', true), ('AGESA.IS', 'AGESA', 'BIST', true), ('AGHOL.IS', 'AGHOL', 'BIST', true), ('AGYO.IS', 'AGYO', 'BIST', true), ('AKBNK.IS', 'AKBNK', 'BIST', true),
('AKCNS.IS', 'AKCNS', 'BIST', true), ('AKENR.IS', 'AKENR', 'BIST', true), ('AKFGY.IS', 'AKFGY', 'BIST', true), ('AKFYE.IS', 'AKFYE', 'BIST', true), ('AKGRT.IS', 'AKGRT', 'BIST', true),
('AKMGY.IS', 'AKMGY', 'BIST', true), ('AKSA.IS', 'AKSA', 'BIST', true), ('AKSEN.IS', 'AKSEN', 'BIST', true), ('AKSYG.IS', 'AKSYG', 'BIST', true), ('ALARK.IS', 'ALARK', 'BIST', true),
('ALBRK.IS', 'ALBRK', 'BIST', true), ('ALCTL.IS', 'ALCTL', 'BIST', true), ('ALFAS.IS', 'ALFAS', 'BIST', true), ('ALGYO.IS', 'ALGYO', 'BIST', true), ('ALKA.IS', 'ALKA', 'BIST', true),
('ALKIM.IS', 'ALKIM', 'BIST', true), ('ALMAD.IS', 'ALMAD', 'BIST', true), ('ANELE.IS', 'ANELE', 'BIST', true), ('ANGEN.IS', 'ANGEN', 'BIST', true), ('ANHYT.IS', 'ANHYT', 'BIST', true),
('ANSGR.IS', 'ANSGR', 'BIST', true), ('ARASE.IS', 'ARASE', 'BIST', true), ('ARCLK.IS', 'ARCLK', 'BIST', true), ('ARDYZ.IS', 'ARDYZ', 'BIST', true), ('ARENA.IS', 'ARENA', 'BIST', true),
('ARSAN.IS', 'ARSAN', 'BIST', true), ('ARZUM.IS', 'ARZUM', 'BIST', true), ('ASELS.IS', 'ASELS', 'BIST', true), ('ASGYO.IS', 'ASGYO', 'BIST', true), ('ASTOR.IS', 'ASTOR', 'BIST', true),
('ASUZU.IS', 'ASUZU', 'BIST', true), ('ATAGY.IS', 'ATAGY', 'BIST', true), ('ATATP.IS', 'ATATP', 'BIST', true), ('ATEK.IS', 'ATEK', 'BIST', true), ('ATLAS.IS', 'ATLAS', 'BIST', true),
('ATSYH.IS', 'ATSYH', 'BIST', true), ('AVGYO.IS', 'AVGYO', 'BIST', true), ('AVHOL.IS', 'AVHOL', 'BIST', true), ('AVOD.IS', 'AVOD', 'BIST', true), ('AVTUR.IS', 'AVTUR', 'BIST', true),
('AYCES.IS', 'AYCES', 'BIST', true), ('AYDEM.IS', 'AYDEM', 'BIST', true), ('AYEN.IS', 'AYEN', 'BIST', true), ('AYGAZ.IS', 'AYGAZ', 'BIST', true), ('AZTEK.IS', 'AZTEK', 'BIST', true),
('BAGFS.IS', 'BAGFS', 'BIST', true), ('BAKAB.IS', 'BAKAB', 'BIST', true), ('BALAT.IS', 'BALAT', 'BIST', true), ('BANVT.IS', 'BANVT', 'BIST', true), ('BARMA.IS', 'BARMA', 'BIST', true),
('BASCM.IS', 'BASCM', 'BIST', true), ('BASGZ.IS', 'BASGZ', 'BIST', true), ('BAYRK.IS', 'BAYRK', 'BIST', true), ('BERA.IS', 'BERA', 'BIST', true), ('BEYAZ.IS', 'BEYAZ', 'BIST', true),
('BFREN.IS', 'BFREN', 'BIST', true), ('BIENP.IS', 'BIENP', 'BIST', true), ('BIGCH.IS', 'BIGCH', 'BIST', true), ('BIMAS.IS', 'BIMAS', 'BIST', true), ('BIOEN.IS', 'BIOEN', 'BIST', true),
('BIZIM.IS', 'BIZIM', 'BIST', true), ('BJKAS.IS', 'BJKAS', 'BIST', true), ('BLCYT.IS', 'BLCYT', 'BIST', true), ('BMSCH.IS', 'BMSCH', 'BIST', true), ('BMSTL.IS', 'BMSTL', 'BIST', true),
('BOBET.IS', 'BOBET', 'BIST', true), ('BRISA.IS', 'BRISA', 'BIST', true), ('BRKO.IS', 'BRKO', 'BIST', true), ('BRKSN.IS', 'BRKSN', 'BIST', true), ('BRKVY.IS', 'BRKVY', 'BIST', true),
('BRLSM.IS', 'BRLSM', 'BIST', true), ('BRMEN.IS', 'BRMEN', 'BIST', true), ('BRSAN.IS', 'BRSAN', 'BIST', true), ('BRYAT.IS', 'BRYAT', 'BIST', true), ('BSOKE.IS', 'BSOKE', 'BIST', true),
('BTCIM.IS', 'BTCIM', 'BIST', true), ('BUCIM.IS', 'BUCIM', 'BIST', true), ('BURCE.IS', 'BURCE', 'BIST', true), ('BURVA.IS', 'BURVA', 'BIST', true), ('BVSAN.IS', 'BVSAN', 'BIST', true),
('BYDNR.IS', 'BYDNR', 'BIST', true), ('CANTE.IS', 'CANTE', 'BIST', true), ('CASA.IS', 'CASA', 'BIST', true), ('CCOLA.IS', 'CCOLA', 'BIST', true), ('CELHA.IS', 'CELHA', 'BIST', true),
('CEMAS.IS', 'CEMAS', 'BIST', true), ('CEMTS.IS', 'CEMTS', 'BIST', true), ('CEOEM.IS', 'CEOEM', 'BIST', true), ('CIMSA.IS', 'CIMSA', 'BIST', true), ('CLEBI.IS', 'CLEBI', 'BIST', true),
('CMBTN.IS', 'CMBTN', 'BIST', true), ('CMENT.IS', 'CMENT', 'BIST', true), ('CONSE.IS', 'CONSE', 'BIST', true), ('COSMO.IS', 'COSMO', 'BIST', true), ('CRDFA.IS', 'CRDFA', 'BIST', true),
('CRFSA.IS', 'CRFSA', 'BIST', true), ('CUSAN.IS', 'CUSAN', 'BIST', true), ('CVKMD.IS', 'CVKMD', 'BIST', true), ('CWENE.IS', 'CWENE', 'BIST', true), ('DAGHL.IS', 'DAGHL', 'BIST', true),
('DAGI.IS', 'DAGI', 'BIST', true), ('DAPGM.IS', 'DAPGM', 'BIST', true), ('DARDL.IS', 'DARDL', 'BIST', true), ('DGATE.IS', 'DGATE', 'BIST', true), ('DGGYO.IS', 'DGGYO', 'BIST', true),
('DGNMO.IS', 'DGNMO', 'BIST', true), ('DIRIT.IS', 'DIRIT', 'BIST', true), ('DITAS.IS', 'DITAS', 'BIST', true), ('DMSAS.IS', 'DMSAS', 'BIST', true), ('DNISI.IS', 'DNISI', 'BIST', true),
('DOAS.IS', 'DOAS', 'BIST', true), ('DOCO.IS', 'DOCO', 'BIST', true), ('DOGUB.IS', 'DOGUB', 'BIST', true), ('DOHOL.IS', 'DOHOL', 'BIST', true), ('DOKTA.IS', 'DOKTA', 'BIST', true),
('DURDO.IS', 'DURDO', 'BIST', true), ('DYOBY.IS', 'DYOBY', 'BIST', true), ('DZGYO.IS', 'DZGYO', 'BIST', true), ('EBEBK.IS', 'EBEBK', 'BIST', true), ('ECILC.IS', 'ECILC', 'BIST', true),
('ECZYT.IS', 'ECZYT', 'BIST', true), ('EDATA.IS', 'EDATA', 'BIST', true), ('EDIP.IS', 'EDIP', 'BIST', true), ('EGEEN.IS', 'EGEEN', 'BIST', true), ('EGEPO.IS', 'EGEPO', 'BIST', true),
('EGGUB.IS', 'EGGUB', 'BIST', true), ('EGPRO.IS', 'EGPRO', 'BIST', true), ('EGSER.IS', 'EGSER', 'BIST', true), ('EKGYO.IS', 'EKGYO', 'BIST', true), ('EKSUN.IS', 'EKSUN', 'BIST', true),
('ELITE.IS', 'ELITE', 'BIST', true), ('EMKEL.IS', 'EMKEL', 'BIST', true), ('ENERY.IS', 'ENERY', 'BIST', true), ('ENJSA.IS', 'ENJSA', 'BIST', true), ('ENKAI.IS', 'ENKAI', 'BIST', true),
('EPLAS.IS', 'EPLAS', 'BIST', true), ('ERBOS.IS', 'ERBOS', 'BIST', true), ('EREGL.IS', 'EREGL', 'BIST', true), ('ERSU.IS', 'ERSU', 'BIST', true), ('ESCOM.IS', 'ESCOM', 'BIST', true),
('ESEN.IS', 'ESEN', 'BIST', true), ('ETILR.IS', 'ETILR', 'BIST', true), ('EUHOL.IS', 'EUHOL', 'BIST', true), ('EUKYO.IS', 'EUKYO', 'BIST', true), ('EUPWR.IS', 'EUPWR', 'BIST', true),
('EUREN.IS', 'EUREN', 'BIST', true), ('EYGYO.IS', 'EYGYO', 'BIST', true), ('FADE.IS', 'FADE', 'BIST', true), ('FENER.IS', 'FENER', 'BIST', true), ('FLAP.IS', 'FLAP', 'BIST', true),
('FMIZP.IS', 'FMIZP', 'BIST', true), ('FONET.IS', 'FONET', 'BIST', true), ('FORMT.IS', 'FORMT', 'BIST', true), ('FROTO.IS', 'FROTO', 'BIST', true), ('FZLGY.IS', 'FZLGY', 'BIST', true),
('GARAN.IS', 'GARAN', 'BIST', true), ('GBYAS.IS', 'GBYAS', 'BIST', true), ('GENTS.IS', 'GENTS', 'BIST', true), ('GEREL.IS', 'GEREL', 'BIST', true), ('GESAN.IS', 'GESAN', 'BIST', true),
('GIPTA.IS', 'GIPTA', 'BIST', true), ('GLBMD.IS', 'GLBMD', 'BIST', true), ('GLCVY.IS', 'GLCVY', 'BIST', true), ('GLRYH.IS', 'GLRYH', 'BIST', true), ('GLYHO.IS', 'GLYHO', 'BIST', true),
('GSDDE.IS', 'GSDDE', 'BIST', true), ('GSDHO.IS', 'GSDHO', 'BIST', true), ('GSRAY.IS', 'GSRAY', 'BIST', true), ('GUBRF.IS', 'GUBRF', 'BIST', true), ('GWIND.IS', 'GWIND', 'BIST', true),
('GZNMI.IS', 'GZNMI', 'BIST', true), ('HALKB.IS', 'HALKB', 'BIST', true), ('HATEK.IS', 'HATEK', 'BIST', true), ('HEDEF.IS', 'HEDEF', 'BIST', true), ('HEKTS.IS', 'HEKTS', 'BIST', true),
('HKTM.IS', 'HKTM', 'BIST', true), ('HLGYO.IS', 'HLGYO', 'BIST', true), ('HTTBT.IS', 'HTTBT', 'BIST', true), ('HUBVC.IS', 'HUBVC', 'BIST', true), ('HUNER.IS', 'HUNER', 'BIST', true),
('HURGZ.IS', 'HURGZ', 'BIST', true), ('ICBCT.IS', 'ICBCT', 'BIST', true), ('IDGYO.IS', 'IDGYO', 'BIST', true), ('IEYHO.IS', 'IEYHO', 'BIST', true), ('IHEVA.IS', 'IHEVA', 'BIST', true),
('IHGZT.IS', 'IHGZT', 'BIST', true), ('IHLAS.IS', 'IHLAS', 'BIST', true), ('IHLGM.IS', 'IHLGM', 'BIST', true), ('IHYAY.IS', 'IHYAY', 'BIST', true), ('IMASM.IS', 'IMASM', 'BIST', true),
('INDES.IS', 'INDES', 'BIST', true), ('INFO.IS', 'INFO', 'BIST', true), ('INGRM.IS', 'INGRM', 'BIST', true), ('INTEM.IS', 'INTEM', 'BIST', true), ('INVEO.IS', 'INVEO', 'BIST', true),
('INVES.IS', 'INVES', 'BIST', true), ('IPEKE.IS', 'IPEKE', 'BIST', true), ('ISATR.IS', 'ISATR', 'BIST', true), ('ISBTR.IS', 'ISBTR', 'BIST', true), ('ISCTR.IS', 'ISCTR', 'BIST', true),
('ISDMR.IS', 'ISDMR', 'BIST', true), ('ISFIN.IS', 'ISFIN', 'BIST', true), ('ISGSY.IS', 'ISGSY', 'BIST', true), ('ISGYO.IS', 'ISGYO', 'BIST', true), ('ISKPL.IS', 'ISKPL', 'BIST', true),
('ISKUR.IS', 'ISKUR', 'BIST', true), ('ISMEN.IS', 'ISMEN', 'BIST', true), ('ISSEN.IS', 'ISSEN', 'BIST', true), ('ISYAT.IS', 'ISYAT', 'BIST', true), ('IZFAS.IS', 'IZFAS', 'BIST', true),
('IZINV.IS', 'IZINV', 'BIST', true), ('IZMDC.IS', 'IZMDC', 'BIST', true), ('JANTS.IS', 'JANTS', 'BIST', true), ('KAPLM.IS', 'KAPLM', 'BIST', true), ('KAREL.IS', 'KAREL', 'BIST', true),
('KARSN.IS', 'KARSN', 'BIST', true), ('KARTN.IS', 'KARTN', 'BIST', true), ('KARYE.IS', 'KARYE', 'BIST', true), ('KATMR.IS', 'KATMR', 'BIST', true), ('KAYSE.IS', 'KAYSE', 'BIST', true),
('KCAER.IS', 'KCAER', 'BIST', true), ('KCHOL.IS', 'KCHOL', 'BIST', true), ('KENT.IS', 'KENT', 'BIST', true), ('KERVN.IS', 'KERVN', 'BIST', true), ('KERVT.IS', 'KERVT', 'BIST', true),
('KFEIN.IS', 'KFEIN', 'BIST', true), ('KGYO.IS', 'KGYO', 'BIST', true), ('KIMMR.IS', 'KIMMR', 'BIST', true), ('KLGYO.IS', 'KLGYO', 'BIST', true), ('KLMSN.IS', 'KLMSN', 'BIST', true),
('KLNMA.IS', 'KLNMA', 'BIST', true), ('KLRHO.IS', 'KLRHO', 'BIST', true), ('KLSYN.IS', 'KLSYN', 'BIST', true), ('KLYAS.IS', 'KLYAS', 'BIST', true), ('KMPUR.IS', 'KMPUR', 'BIST', true),
('KNFRT.IS', 'KNFRT', 'BIST', true), ('KONKA.IS', 'KONKA', 'BIST', true), ('KONTR.IS', 'KONTR', 'BIST', true), ('KONYA.IS', 'KONYA', 'BIST', true), ('KOPOL.IS', 'KOPOL', 'BIST', true),
('KORDS.IS', 'KORDS', 'BIST', true), ('KOZAA.IS', 'KOZAA', 'BIST', true), ('KOZAL.IS', 'KOZAL', 'BIST', true), ('KRDMA.IS', 'KRDMA', 'BIST', true), ('KRDMB.IS', 'KRDMB', 'BIST', true),
('KRDMD.IS', 'KRDMD', 'BIST', true), ('KRONT.IS', 'KRONT', 'BIST', true), ('KRPLS.IS', 'KRPLS', 'BIST', true), ('KRSTL.IS', 'KRSTL', 'BIST', true), ('KRTEK.IS', 'KRTEK', 'BIST', true),
('KSTUR.IS', 'KSTUR', 'BIST', true), ('KTSKR.IS', 'KTSKR', 'BIST', true), ('KUTPO.IS', 'KUTPO', 'BIST', true), ('KUVVA.IS', 'KUVVA', 'BIST', true), ('KUYAS.IS', 'KUYAS', 'BIST', true),
('KZBGY.IS', 'KZBGY', 'BIST', true), ('KZGYO.IS', 'KZGYO', 'BIST', true), ('LIDER.IS', 'LIDER', 'BIST', true), ('LIDFA.IS', 'LIDFA', 'BIST', true), ('LINK.IS', 'LINK', 'BIST', true),
('LMKDC.IS', 'LMKDC', 'BIST', true), ('LOGAS.IS', 'LOGAS', 'BIST', true), ('LOGO.IS', 'LOGO', 'BIST', true), ('LRSHL.IS', 'LRSHL', 'BIST', true), ('LUKSK.IS', 'LUKSK', 'BIST', true),
('MAALT.IS', 'MAALT', 'BIST', true), ('MACKO.IS', 'MACKO', 'BIST', true), ('MAGEN.IS', 'MAGEN', 'BIST', true), ('MAKIM.IS', 'MAKIM', 'BIST', true), ('MAKTK.IS', 'MAKTK', 'BIST', true),
('MANAS.IS', 'MANAS', 'BIST', true), ('MARKA.IS', 'MARKA', 'BIST', true), ('MARTI.IS', 'MARTI', 'BIST', true), ('MAVI.IS', 'MAVI', 'BIST', true), ('MEDTR.IS', 'MEDTR', 'BIST', true),
('MEGAP.IS', 'MEGAP', 'BIST', true), ('MEPET.IS', 'MEPET', 'BIST', true), ('MERCN.IS', 'MERCN', 'BIST', true), ('MERKO.IS', 'MERKO', 'BIST', true), ('METRO.IS', 'METRO', 'BIST', true),
('METUR.IS', 'METUR', 'BIST', true), ('MGROS.IS', 'MGROS', 'BIST', true), ('MHRGY.IS', 'MHRGY', 'BIST', true), ('MIATK.IS', 'MIATK', 'BIST', true), ('MIPAZ.IS', 'MIPAZ', 'BIST', true),
('MMCAS.IS', 'MMCAS', 'BIST', true), ('MNDRS.IS', 'MNDRS', 'BIST', true), ('MNDTR.IS', 'MNDTR', 'BIST', true), ('MOBTL.IS', 'MOBTL', 'BIST', true), ('MPARK.IS', 'MPARK', 'BIST', true),
('MRGYO.IS', 'MRGYO', 'BIST', true), ('MRSHL.IS', 'MRSHL', 'BIST', true), ('MSGYO.IS', 'MSGYO', 'BIST', true), ('MTRKS.IS', 'MTRKS', 'BIST', true), ('MTRYO.IS', 'MTRYO', 'BIST', true),
('MZHLD.IS', 'MZHLD', 'BIST', true), ('NATEN.IS', 'NATEN', 'BIST', true), ('NETAS.IS', 'NETAS', 'BIST', true), ('NIBAS.IS', 'NIBAS', 'BIST', true), ('NTGAZ.IS', 'NTGAZ', 'BIST', true),
('NTHOL.IS', 'NTHOL', 'BIST', true), ('NUGYO.IS', 'NUGYO', 'BIST', true), ('NUHCM.IS', 'NUHCM', 'BIST', true), ('OBASE.IS', 'OBASE', 'BIST', true), ('OFSYM.IS', 'OFSYM', 'BIST', true),
('ONCSM.IS', 'ONCSM', 'BIST', true), ('ORCAY.IS', 'ORCAY', 'BIST', true), ('ORGE.IS', 'ORGE', 'BIST', true), ('ORMA.IS', 'ORMA', 'BIST', true), ('OSMEN.IS', 'OSMEN', 'BIST', true),
('OSTIM.IS', 'OSTIM', 'BIST', true), ('OTKAR.IS', 'OTKAR', 'BIST', true), ('OYAKC.IS', 'OYAKC', 'BIST', true), ('OYAYO.IS', 'OYAYO', 'BIST', true), ('OYLUM.IS', 'OYLUM', 'BIST', true),
('OYYAT.IS', 'OYYAT', 'BIST', true), ('OZGYO.IS', 'OZGYO', 'BIST', true), ('OZKGY.IS', 'OZKGY', 'BIST', true), ('OZRDN.IS', 'OZRDN', 'BIST', true), ('OZSUB.IS', 'OZSUB', 'BIST', true),
('PAGYO.IS', 'PAGYO', 'BIST', true), ('PAMEL.IS', 'PAMEL', 'BIST', true), ('PAPA.IS', 'PAPA', 'BIST', true), ('PARSN.IS', 'PARSN', 'BIST', true), ('PASEU.IS', 'PASEU', 'BIST', true),
('PATEK.IS', 'PATEK', 'BIST', true), ('PCILT.IS', 'PCILT', 'BIST', true), ('PEGYO.IS', 'PEGYO', 'BIST', true), ('PEKGY.IS', 'PEKGY', 'BIST', true), ('PENGD.IS', 'PENGD', 'BIST', true),
('PENTA.IS', 'PENTA', 'BIST', true), ('PETKM.IS', 'PETKM', 'BIST', true), ('PETUN.IS', 'PETUN', 'BIST', true), ('PGSUS.IS', 'PGSUS', 'BIST', true), ('PINSU.IS', 'PINSU', 'BIST', true),
('PKART.IS', 'PKART', 'BIST', true), ('PKENT.IS', 'PKENT', 'BIST', true), ('PLTUR.IS', 'PLTUR', 'BIST', true), ('PNLSN.IS', 'PNLSN', 'BIST', true), ('PNSUT.IS', 'PNSUT', 'BIST', true),
('POLHO.IS', 'POLHO', 'BIST', true), ('POLTK.IS', 'POLTK', 'BIST', true), ('PRDGS.IS', 'PRDGS', 'BIST', true), ('PRKAB.IS', 'PRKAB', 'BIST', true), ('PRKME.IS', 'PRKME', 'BIST', true),
('PRZMA.IS', 'PRZMA', 'BIST', true), ('PSGYO.IS', 'PSGYO', 'BIST', true), ('QUAGR.IS', 'QUAGR', 'BIST', true), ('RALYH.IS', 'RALYH', 'BIST', true), ('RAYYS.IS', 'RAYYS', 'BIST', true),
('REEDR.IS', 'REEDR', 'BIST', true), ('RNPOL.IS', 'RNPOL', 'BIST', true), ('RODRG.IS', 'RODRG', 'BIST', true), ('ROYAL.IS', 'ROYAL', 'BIST', true), ('RTALB.IS', 'RTALB', 'BIST', true),
('RUBNS.IS', 'RUBNS', 'BIST', true), ('RYGYO.IS', 'RYGYO', 'BIST', true), ('RYSAS.IS', 'RYSAS', 'BIST', true), ('SAFKR.IS', 'SAFKR', 'BIST', true), ('SAHOL.IS', 'SAHOL', 'BIST', true),
('SAMAT.IS', 'SAMAT', 'BIST', true), ('SANEL.IS', 'SANEL', 'BIST', true), ('SANFO.IS', 'SANFO', 'BIST', true), ('SANKO.IS', 'SANKO', 'BIST', true), ('SARKY.IS', 'SARKY', 'BIST', true),
('SASA.IS', 'SASA', 'BIST', true), ('SAYAS.IS', 'SAYAS', 'BIST', true), ('SDTTR.IS', 'SDTTR', 'BIST', true), ('SEKFK.IS', 'SEKFK', 'BIST', true), ('SEKUR.IS', 'SEKUR', 'BIST', true),
('SELEC.IS', 'SELEC', 'BIST', true), ('SELGD.IS', 'SELGD', 'BIST', true), ('SELVA.IS', 'SELVA', 'BIST', true), ('SEYKM.IS', 'SEYKM', 'BIST', true), ('SILVR.IS', 'SILVR', 'BIST', true),
('SISE.IS', 'SISE', 'BIST', true), ('SKBNK.IS', 'SKBNK', 'BIST', true), ('SKTAS.IS', 'SKTAS', 'BIST', true), ('SKYMD.IS', 'SKYMD', 'BIST', true), ('SMART.IS', 'SMART', 'BIST', true),
('SMRTG.IS', 'SMRTG', 'BIST', true), ('SNGYO.IS', 'SNGYO', 'BIST', true), ('SNICA.IS', 'SNICA', 'BIST', true), ('SNKPA.IS', 'SNKPA', 'BIST', true), ('SNPAM.IS', 'SNPAM', 'BIST', true),
('SOKM.IS', 'SOKM', 'BIST', true), ('SONME.IS', 'SONME', 'BIST', true), ('SRVGY.IS', 'SRVGY', 'BIST', true), ('SUWEN.IS', 'SUWEN', 'BIST', true), ('TABGD.IS', 'TABGD', 'BIST', true),
('TARKM.IS', 'TARKM', 'BIST', true), ('TATEN.IS', 'TATEN', 'BIST', true), ('TATGD.IS', 'TATGD', 'BIST', true), ('TAVHL.IS', 'TAVHL', 'BIST', true), ('TCELL.IS', 'TCELL', 'BIST', true),
('TDGYO.IS', 'TDGYO', 'BIST', true), ('TEKTU.IS', 'TEKTU', 'BIST', true), ('TERA.IS', 'TERA', 'BIST', true), ('TETMT.IS', 'TETMT', 'BIST', true), ('TGSAS.IS', 'TGSAS', 'BIST', true),
('THYAO.IS', 'THYAO', 'BIST', true), ('TIRE.IS', 'TIRE', 'BIST', true), ('TKFEN.IS', 'TKFEN', 'BIST', true), ('TKNSA.IS', 'TKNSA', 'BIST', true), ('TLSAS.IS', 'TLSAS', 'BIST', true),
('TMPOL.IS', 'TMPOL', 'BIST', true), ('TMSN.IS', 'TMSN', 'BIST', true), ('TOASO.IS', 'TOASO', 'BIST', true), ('TRCAS.IS', 'TRCAS', 'BIST', true), ('TRGYO.IS', 'TRGYO', 'BIST', true),
('TRILC.IS', 'TRILC', 'BIST', true), ('TSKB.IS', 'TSKB', 'BIST', true), ('TSPOR.IS', 'TSPOR', 'BIST', true), ('TTKOM.IS', 'TTKOM', 'BIST', true), ('TTRAK.IS', 'TTRAK', 'BIST', true),
('TUCLK.IS', 'TUCLK', 'BIST', true), ('TUKAS.IS', 'TUKAS', 'BIST', true), ('TUPRS.IS', 'TUPRS', 'BIST', true), ('TUREX.IS', 'TUREX', 'BIST', true), ('TURGG.IS', 'TURGG', 'BIST', true),
('TURSG.IS', 'TURSG', 'BIST', true), ('UFUK.IS', 'UFUK', 'BIST', true), ('ULAS.IS', 'ULAS', 'BIST', true), ('ULUSE.IS', 'ULUSE', 'BIST', true), ('ULUFA.IS', 'ULUFA', 'BIST', true),
('ULUN.IS', 'ULUN', 'BIST', true), ('UMPAS.IS', 'UMPAS', 'BIST', true), ('UNLU.IS', 'UNLU', 'BIST', true), ('USAK.IS', 'USAK', 'BIST', true), ('VAKBN.IS', 'VAKBN', 'BIST', true),
('VAKFN.IS', 'VAKFN', 'BIST', true), ('VAKKO.IS', 'VAKKO', 'BIST', true), ('VANGD.IS', 'VANGD', 'BIST', true), ('VBTYZ.IS', 'VBTYZ', 'BIST', true), ('VERTU.IS', 'VERTU', 'BIST', true),
('VERUS.IS', 'VERUS', 'BIST', true), ('VESBE.IS', 'VESBE', 'BIST', true), ('VESTL.IS', 'VESTL', 'BIST', true), ('VKGYO.IS', 'VKGYO', 'BIST', true), ('VKING.IS', 'VKING', 'BIST', true),
('YAPRK.IS', 'YAPRK', 'BIST', true), ('YATAS.IS', 'YATAS', 'BIST', true), ('YAYLA.IS', 'YAYLA', 'BIST', true), ('YBTAS.IS', 'YBTAS', 'BIST', true), ('YEOTK.IS', 'YEOTK', 'BIST', true),
('YESIL.IS', 'YESIL', 'BIST', true), ('YGGYO.IS', 'YGGYO', 'BIST', true), ('YGYO.IS', 'YGYO', 'BIST', true), ('YKBNK.IS', 'YKBNK', 'BIST', true), ('YKSLN.IS', 'YKSLN', 'BIST', true),
('YONGA.IS', 'YONGA', 'BIST', true), ('YOTAS.IS', 'YOTAS', 'BIST', true), ('YUNSA.IS', 'YUNSA', 'BIST', true), ('YYAPI.IS', 'YYAPI', 'BIST', true), ('YYLGD.IS', 'YYLGD', 'BIST', true),
('ZEDUR.IS', 'ZEDUR', 'BIST', true), ('ZOREN.IS', 'ZOREN', 'BIST', true), ('ZRGYO.IS', 'ZRGYO', 'BIST', true)
ON CONFLICT (symbol) DO NOTHING;
