package com.antigravity.mobile.domain.util

/**
 * Borsa İstanbul (BIST) hisse senetleri sembol - şirket unvanı eşleşme tablosu.
 * UI'da hisse kodunun altında şirketin tam/uzun ismini göstermek için kullanılır.
 */
object BistCompanyNames {

    private val companyNames: Map<String, String> = mapOf(
        "A1CAP" to "A1 Capital Yatırım Menkul Değerler",
        "A1YEN" to "A1 Yenilenebilir Enerji",
        "ACSEL" to "Acıselsan Acıpayam Selüloz",
        "ADEL" to "Adel Kalemcilik",
        "ADESE" to "Adese Gayrimenkul Yatırım",
        "ADGYO" to "Adra Gayrimenkul Yatırım Ortaklığı",
        "AEFES" to "Anadolu Efes Biracılık ve Malt Sanayii",
        "AFYON" to "Afyon Çimento",
        "AGESA" to "AgeSA Hayat ve Emeklilik",
        "AGHOL" to "AG Anadolu Grubu Holding",
        "AGROT" to "Agrotech Yüksek Teknoloji",
        "AGYO" to "Atakule Gayrimenkul Yatırım Ortaklığı",
        "AHGAZ" to "Ahlatcı Doğal Gaz Dağıtım",
        "AHSGY" to "Ahlatcı Gayrimenkul Yatırım Ortaklığı",
        "AKBNK" to "Akbank T.A.Ş.",
        "AKCNS" to "Akçansa Çimento Sanayi ve Ticaret",
        "AKENR" to "Akenerji Elektrik Üretim",
        "AKFIS" to "Akfen İnşaat Turizm ve İşletmecilik",
        "AKFGY" to "Akfen Gayrimenkul Yatırım Ortaklığı",
        "AKFYE" to "Akfen Yenilenebilir Enerji",
        "AKGRT" to "Aksigorta",
        "AKHAN" to "Akın Hayvancılık",
        "AKMGY" to "Akmerkez Gayrimenkul Yatırım Ortaklığı",
        "AKSA" to "Aksa Akrilik Kimya Sanayii",
        "AKSEN" to "Aksa Enerji Üretim",
        "AKSUE" to "Aksu Enerji ve Ticaret",
        "AKSYG" to "Aksigorta",
        "AKYHO" to "Akdeniz Yatırım Holding",
        "ALARK" to "Alarko Holding",
        "ALBRK" to "Albaraka Türk Katılım Bankası",
        "ALCAR" to "Alarko Carrier Sanayi ve Ticaret",
        "ALCTL" to "Alcatel Lucent Teletaş Telekomünikasyon",
        "ALFAS" to "Alfa Solar Enerji Sanayi ve Ticaret",
        "ALGYO" to "Alarko Gayrimenkul Yatırım Ortaklığı",
        "ALKA" to "Alkim Kağıt Sanayi ve Ticaret",
        "ALKIM" to "Alkim Alkali Kimya",
        "ALKLC" to "Alkazar Teknoloji",
        "ALMAD" to "Altınyağ Madencilik ve Enerji Yatırımları",
        "ALTIN" to "Darphane Altın Sertifikası",
        "ALTNY" to "Altınay Savunma Teknolojileri",
        "ALVES" to "Alves Kablo Sanayi ve Ticaret",
        "ANELE" to "Anel Elektrik Proje Taahhüt ve Ticaret",
        "ANGEN" to "Anatolia Tanı ve Biyoteknoloji Ürünleri",
        "ANHYT" to "Anadolu Hayat Emeklilik",
        "ANSGR" to "Anadolu Sigorta",
        "ARASE" to "Doğu Aras Enerji Yatırımları",
        "ARCLK" to "Arçelik A.Ş.",
        "ARDYZ" to "ARD Grup Bilişim Teknolojileri",
        "ARENA" to "Arena Bilgisayar Sanayi ve Ticaret",
        "ARFYE" to "Arf Finansal Yatırımlar",
        "ARMGD" to "Armada Gıda Ticaret Sanayi",
        "ARSAN" to "Arsan Tekstil Ticaret ve Sanayi",
        "ARTMS" to "Artemis Halı",
        "ARZUM" to "Arzum Elektrikli Ev Aletleri",
        "ASELS" to "Aselsan Elektronik Sanayi ve Ticaret",
        "ASGYO" to "Asce Gayrimenkul Yatırım Ortaklığı",
        "ASTOR" to "Astor Enerji",
        "ASUZU" to "Anadolu Isuzu Otomotiv Sanayi",
        "ATAGY" to "Ata Gayrimenkul Yatırım Ortaklığı",
        "ATAKP" to "Atakey Patates Gıda Sanayi",
        "ATATP" to "ATP Yazılım ve Teknoloji",
        "ATATR" to "Ata Gayrimenkul",
        "ATEK" to "Akın Tekstil",
        "ATEKS" to "Akın Tekstil",
        "ATLAS" to "Atlas Menkul Kıymetler Yatırım Ortaklığı",
        "ATSYH" to "Atlantis Yatırım Holding",
        "AVGYO" to "Avrasya Gayrimenkul Yatırım Ortaklığı",
        "AVHOL" to "Avrupa Yatırım Holding",
        "AVOD" to "A.V.O.D. Kurutulmuş Gıda ve Tarım Ürünleri",
        "AVTUR" to "Avrasya Petrol ve Turistik Tesisler",
        "AYCES" to "Altın Yunus Çeşme Turistik Tesisler",
        "AYDEM" to "Aydem Yenilenebilir Enerji",
        "AYEN" to "Ayen Enerji",
        "AYES" to "Ayes Çelik Hasır ve Çit Sanayi",
        "AYGAZ" to "Aygaz A.Ş.",
        "AZTEK" to "Aztek Teknoloji Ürünleri Ticaret",
        "BAGFS" to "Bağfaş Bandırma Gübre Fabrikaları",
        "BAHKM" to "Bahadır Kimya Sanayi ve Ticaret",
        "BAKAB" to "Bak Ambalaj Sanayi ve Ticaret",
        "BALAT" to "Balatacılar Balatacılık Sanayi",
        "BALSU" to "Balsu Gıda Sanayi ve Ticaret",
        "BANVT" to "Banvit Bandırma Vitaminli Yem Sanayii",
        "BARMA" to "Barem Ambalaj Sanayi ve Ticaret",
        "BASCM" to "Baştaş Başkent Çimento Sanayi",
        "BASGZ" to "Başkent Doğalgaz Dağıtım",
        "BAYRK" to "Bayrak Ebt Taban Sanayi ve Ticaret",
        "BEGYO" to "Batı Ege Gayrimenkul Yatırım Ortaklığı",
        "BERA" to "Bera Holding",
        "BESLR" to "Besler Tekstil Sanayi",
        "BESTE" to "Bestepe Finansal Hizmetler",
        "BEYAZ" to "Beyaz Filo Oto Kiralama",
        "BFREN" to "Bosch Fren Sistemleri Sanayi ve Ticaret",
        "BIENP" to "Bien Yapı Ürünleri Sanayi Turizm",
        "BIENY" to "Bien Yapı Ürünleri Sanayi Turizm",
        "BIGCH" to "Big Chefs (Büyük Şefler Gıda)",
        "BIGEN" to "Bigen Biyoteknoloji",
        "BIGTK" to "Big Teknoloji",
        "BIMAS" to "BİM Birleşik Mağazalar",
        "BINBN" to "Bin Ulaşım ve Akıllı Şehir (BinBin)",
        "BINHO" to "1000 Yatırımlar Holding",
        "BIOEN" to "Biotrend Çevre ve Enerji Yatırımları",
        "BIZIM" to "Bizim Toptan Satış Mağazaları",
        "BJKAS" to "Beşiktaş Futbol Yatırımları Sanayi",
        "BLCYT" to "Bilici Yatırım Sanayi ve Ticaret",
        "BLUME" to "Blume Gayrimenkul",
        "BMSCH" to "BMS Çelik Hasır Sanayi ve Ticaret",
        "BMSTL" to "BMS Birleşik Metal Sanayi",
        "BNTAS" to "Bantaş Bandırma Ambalaj Sanayi",
        "BOBET" to "Boğaziçi Beton Sanayi ve Ticaret",
        "BORLS" to "Borlease Otomotiv",
        "BORSK" to "Bor Şeker A.Ş.",
        "BOSSA" to "Bossa Ticaret ve Sanayi İşletmeleri",
        "BRISA" to "Brisa Bridgestone Sabancı Lastik Sanayi",
        "BRKO" to "Birko Birleşik Koyunlulular Mensucat",
        "BRKSN" to "Berkosan Yalıtım ve Tecrit Maddeleri",
        "BRKVY" to "Birikim Varlık Yönetim",
        "BRLSM" to "Birleşim Mühendislik Isıtma Soğutma",
        "BRMEN" to "Birlik Mensucat Ticaret ve Sanayi",
        "BRSAN" to "Borusan Birleşik Boru Fabrikaları",
        "BRYAT" to "Borusan Yatırım ve Pazarlama",
        "BSOKE" to "Batısöke Söke Çimento Sanayii",
        "BTCIM" to "Batıçim Batı Anadolu Çimento Sanayii",
        "BUCIM" to "Bursa Çimento Fabrikası",
        "BULGS" to "Bulut Gayrimenkul",
        "BURCE" to "Burçelik Bursa Çelik Döküm Sanayi",
        "BURVA" to "Burçelik Vana Sanayi ve Ticaret",
        "BVSAN" to "Bülbüloğlu Vinç Sanayi",
        "BYDNR" to "Baydöner Restoranları",
        "CANTE" to "Çan2 Termik A.Ş.",
        "CASA" to "Casa Emtia Petrol Kimyevi ve Türevleri",
        "CATES" to "Çates Elektrik Üretim",
        "CCOLA" to "Coca-Cola İçecek A.Ş.",
        "CELHA" to "Çelik Halat ve Tel Sanayii",
        "CEMAS" to "Çemaş Döküm Sanayi",
        "CEMTS" to "Çemtaş Çelik Makina Sanayi ve Ticaret",
        "CEMZY" to "Çemzy Gayrimenkul",
        "CEOEM" to "CEO Event Medya",
        "CGCAM" to "CG Cam Endüstrisi",
        "CIMSA" to "Çimsa Çimento Sanayi ve Ticaret",
        "CLEBI" to "Çelebi Hava Servisi",
        "CMBTN" to "Çimbeton Hazırbeton ve Prefabrik",
        "CMENT" to "Çimentaş İzmir Çimento Fabrikası",
        "CONSE" to "Consus Enerji İşletmeciliği",
        "COSMO" to "Cosmos Yatırım Holding",
        "CRDFA" to "Creditwest Faktoring",
        "CRFSA" to "CarrefourSA Sabancı Ticaret Merkezi",
        "CUSAN" to "Çuhadaroğlu Metal Sanayi ve Pazarlama",
        "CVKMD" to "CVK Maden İşletmeleri Sanayi ve Ticaret",
        "CWENE" to "CW Enerji Mühendislik Ticaret ve Sanayi",
        "DAGHL" to "Dagi Yatırım Holding",
        "DAGI" to "Dagi Giyim Sanayi ve Ticaret",
        "DAPGM" to "Dap Gayrimenkul Geliştirme",
        "DARDL" to "Dardanel Önentaş Gıda Sanayi",
        "DCTTR" to "DCT Trading Dış Ticaret",
        "DENGE" to "Denge Yatırım Holding",
        "DERHL" to "Derlüks Yatırım Holding",
        "DERIM" to "Derimod Konfeksiyon Ayakkabı Deri Sanayi",
        "DESA" to "Desa Deri Sanayi ve Ticaret",
        "DESPC" to "Despec Bilgisayar Pazarlama ve Ticaret",
        "DEVA" to "Deva Holding",
        "DGATE" to "Datagate Bilgisayar Malzemeleri Ticaret",
        "DGGYO" to "Doğuş Gayrimenkul Yatırım Ortaklığı",
        "DGNMO" to "Doğanlar Mobilya Grubu İmalat Sanayi",
        "DIRIT" to "Ditaş Doğan Yedek Parça İmalat",
        "DITAS" to "Ditaş Doğan Yedek Parça İmalat",
        "DMLKT" to "Damla Kent Gayrimenkul",
        "DMRGD" to "DMR Unlu Mamuller (Simit Sarayı)",
        "DMSAS" to "Demisaş Döküm Emaye Mamulleri Sanayi",
        "DNISI" to "Dinamik Isı Makina Yalıtım Malzemeleri",
        "DOAS" to "Doğuş Otomotiv Servis ve Ticaret",
        "DOFER" to "Dofer Yapı Malzemeleri Sanayi ve Ticaret",
        "DOFRB" to "Dofer B Sanayi",
        "DOCO" to "DO & CO AG",
        "DOGUB" to "Doğusan Boru Sanayi ve Ticaret",
        "DOHOL" to "Doğan Şirketler Grubu Holding",
        "DOKTA" to "Döktaş Dökümcülük Ticaret ve Sanayi",
        "DSTKF" to "Destek Finans Faktoring",
        "DUNYH" to "Dünya Holding",
        "DURDO" to "Duran Doğan Basım ve Ambalaj Sanayi",
        "DURKN" to "Durukan Şekerleme Sanayi ve Ticaret",
        "DYOBY" to "Dyo Boya Fabrikaları Sanayi ve Ticaret",
        "DZGYO" to "Deniz Gayrimenkul Yatırım Ortaklığı",
        "EBEBK" to "Ebebek Mağazacılık",
        "ECILC" to "Eczacıbaşı İlaç Sınai ve Finansal Yatırımlar",
        "ECOGR" to "Eco Gayrimenkul",
        "ECZYT" to "Eczacıbaşı Yatırım Holding Ortaklığı",
        "EDATA" to "E-Data Teknoloji Geliştirme",
        "EDIP" to "Edip Gayrimenkul Yatırım Sanayi ve Ticaret",
        "EFOR" to "Efor Çay Sanayi Ticaret",
        "EGEEN" to "Ege Endüstri ve Ticaret",
        "EGEGY" to "Ege Gayrimenkul",
        "EGEPO" to "Nasmed Egepol Sağlık Hizmetleri",
        "EGGUB" to "Ege Gübre Sanayii",
        "EGPRO" to "Ege Profil Ticaret ve Sanayi",
        "EGSER" to "Ege Seramik Sanayi ve Ticaret",
        "EKIZ" to "Ekiz Kimya Sanayi ve Ticaret",
        "EKGYO" to "Emlak Konut Gayrimenkul Yatırım Ortaklığı",
        "EKOS" to "Ekos Teknoloji ve Elektrik",
        "EKSUN" to "Eksun Gıda Tarım Sanayi ve Ticaret",
        "ELITE" to "Elite Naturel Organik Gıda Sanayi",
        "EMKEL" to "Emek Elektrik Endüstrisi",
        "EMNIS" to "Eminiş Ambalaj Sanayi ve Ticaret",
        "EMPAE" to "Empa Elektronik Sanayi",
        "ENDAE" to "Enda Enerji Holding",
        "ENERY" to "Enerya Enerji A.Ş.",
        "ENJSA" to "Enerjisa Enerji A.Ş.",
        "ENKAI" to "Enka İnşaat ve Sanayi",
        "ENSRI" to "Ensari Deri Gıda Sanayi ve Ticaret",
        "ENTRA" to "IC Enterra Yenilenebilir Enerji",
        "EPLAS" to "Egeplast Ege Plastik Ticaret ve Sanayi",
        "ERBOS" to "Erbosan Erciyas Boru Sanayii ve Ticaret",
        "ERCB" to "Erciyas Çelik Boru Sanayi",
        "EREGL" to "Ereğli Demir ve Çelik Fabrikaları",
        "ERSU" to "Ersu Meyve Suları Sarmaşık Konserve",
        "ESCAR" to "Escar Turizm Taşımacılık Ticaret",
        "ESCOM" to "Escort Teknoloji Yatırım",
        "ESEN" to "Esenboğa Elektrik Üretim",
        "ETILR" to "Etiler Gıda ve Ticari Yatırımlar",
        "ETYAT" to "Euro Trend Yatırım Ortaklığı",
        "EUHOL" to "Euro Yatırım Holding",
        "EUKYO" to "Euro Menkul Kıymetler Yatırım Ortaklığı",
        "EUPWR" to "Europower Enerji ve Otomasyon Teknolojileri",
        "EUREN" to "Europen Endüstri Sanayi ve Ticaret",
        "EUYO" to "Euro Yatırım Ortaklığı",
        "EYGYO" to "EYG Gayrimenkul Yatırım Ortaklığı",
        "FADE" to "Fade Gıda Yatırım Sanayi ve Ticaret",
        "FENER" to "Fenerbahçe Futbol A.Ş.",
        "FLAP" to "Flap Kongre Toplantı Hizmetleri Otomotiv ve Turizm",
        "FMIZP" to "Federal-Mogul İzmit Piston ve Pim Üretim",
        "FONET" to "Fonet Bilgi Teknolojileri",
        "FORMT" to "Formet Metal ve Cam Sanayi",
        "FORTE" to "Forte Bilgi İletişim Teknolojileri ve Savunma",
        "FRIGO" to "Frigo-Pak Gıda Maddeleri Sanayi ve Ticaret",
        "FRMPL" to "Form Plastik Sanayi",
        "FROTO" to "Ford Otomotiv Sanayi A.Ş.",
        "FZLGY" to "Fuzul Gayrimenkul Yatırım Ortaklığı",
        "GARAN" to "Türkiye Garanti Bankası (Garanti BBVA)",
        "GARFA" to "Garanti Faktoring",
        "GATEG" to "Gateks İplik Sanayi",
        "GBYAS" to "Gür-Sel Turizm Yatırım",
        "GEDIK" to "Gedik Yatırım Menkul Değerler",
        "GEDZA" to "Gediz Ambalaj Sanayi ve Ticaret",
        "GENIL" to "Gen İlaç ve Sağlık Ürünleri Sanayi",
        "GENKM" to "Genkim Kimya Sanayi",
        "GENTS" to "Gentaş Dekoratif Yüzeyler Sanayi ve Ticaret",
        "GEREL" to "Gersan Elektrik Ticaret ve Sanayi",
        "GESAN" to "Girişim Elektrik Sanayi Taahhüt ve Ticaret",
        "GIPTA" to "Gıpta Ofis Kırtasiye ve Promosyon Ürünleri",
        "GLBMD" to "Global Menkul Değerler",
        "GLCVY" to "Gelecek Varlık Yönetimi",
        "GLRMK" to "Gülermak Ağır Sanayi İnşaat",
        "GLRYH" to "Güler Yatırım Holding",
        "GLYHO" to "Global Yatırım Holding",
        "GMTAS" to "Gimat Mağazacılık Sanayi ve Ticaret",
        "GOKNR" to "Göknur Gıda Maddeleri Enerji İmalat",
        "GOLTS" to "Göltaş Göller Bölgesi Çimento Sanayi",
        "GOODY" to "Good-Year Lastikleri Türk A.Ş.",
        "GOZDE" to "Gözde Girişim Sermayesi Yatırım Ortaklığı",
        "GRNYO" to "Garanti Yatırım Ortaklığı",
        "GRSEL" to "Gürsel Turizm Taşımacılık ve Servis",
        "GRTHO" to "Güriş Holding",
        "GSDDE" to "GSD Denizcilik Gayrimenkul İnşaat Sanayi",
        "GSDHO" to "GSD Holding",
        "GSRAY" to "Galatasaray Sportif Sınai ve Ticari Yatırımlar",
        "GUBRF" to "Gübre Fabrikaları T.A.Ş.",
        "GUNDG" to "Gündoğdu Gıda Süt Ürünleri Sanayi",
        "GWIND" to "Galata Wind Enerji A.Ş.",
        "GZNMI" to "Gezinomi Seyahat Turizm Finansal Hizmetler",
        "HALKB" to "Türkiye Halk Bankası A.Ş.",
        "HATEK" to "Hateks Hatay Tekstil İşletmeleri",
        "HATSN" to "Hatsan Gemi İnşaa Bakım Onarım Deniz Nakliyat",
        "HDFGS" to "Hedef Girişim Sermayesi Yatırım Ortaklığı",
        "HEDEF" to "Hedef Holding",
        "HEKTS" to "Hektaş Ticaret T.A.Ş.",
        "HKTM" to "Hidropar Hareket Kontrol Teknolojileri",
        "HLGYO" to "Halk Gayrimenkul Yatırım Ortaklığı",
        "HOROZ" to "Horoz Lojistik Kargo Hizmetleri",
        "HRKET" to "Hareket Proje Taşımacılığı ve Yük Mühendisliği",
        "HTTBT" to "Hitit Bilgisayar Hizmetleri",
        "HUBVC" to "Hub Girişim Sermayesi Yatırım Ortaklığı",
        "HUNER" to "Hun Yenilenebilir Enerji Üretim",
        "HURGZ" to "Hürriyet Gazetecilik ve Matbaacılık",
        "ICBCT" to "ICBC Turkey Bank A.Ş.",
        "ICUGS" to "İcu Girişim Sermayesi Yatırım Ortaklığı",
        "IDGYO" to "İdealist Gayrimenkul Yatırım Ortaklığı",
        "IEYHO" to "Işıklar Enerji ve Yapı Holding",
        "IHAAS" to "İhlas Haber Ajansı",
        "IHEVA" to "İhlas Ev Aletleri İmalat Sanayi ve Ticaret",
        "IHGZT" to "İhlas Gazetecilik",
        "IHLAS" to "İhlas Holding",
        "IHLGM" to "İhlas Gayrimenkul Proje Geliştirme",
        "IHYAY" to "İhlas Yayın Holding",
        "IMASM" to "İmaş Makina Sanayi",
        "INDES" to "İndeks Bilgisayar Sistemleri Mühendislik",
        "INFO" to "İnfo Yatırım Menkul Değerler",
        "INGRM" to "Ingram Micro Bilişim Sistemleri",
        "INTEK" to "İntek Bilişim ve Teknoloji",
        "INTEM" to "İntema İnşaat ve Tesisat Malzemeleri Yatırım",
        "INVEO" to "Inveo Yatırım Holding",
        "INVES" to "Investco Holding",
        "IPEKE" to "İpek Doğal Enerji Kaynakları Araştırma",
        "ISATR" to "Türkiye İş Bankası (A)",
        "ISBIR" to "İşbir Holding",
        "ISBTR" to "Türkiye İş Bankası (B)",
        "ISCTR" to "Türkiye İş Bankası (C)",
        "ISDMR" to "İskenderun Demir ve Çelik A.Ş.",
        "ISFIN" to "İş Finansal Kiralama",
        "ISGSY" to "İş Girişim Sermayesi Yatırım Ortaklığı",
        "ISGYO" to "İş Gayrimenkul Yatırım Ortaklığı",
        "ISKPL" to "Işık Plastik Sanayi ve Dış Ticaret Pazarlama",
        "ISKUR" to "Türkiye İş Bankası (Kurucu)",
        "ISMEN" to "İş Yatırım Menkul Değerler",
        "ISSEN" to "İşbir Sentetik Dokuma Sanayi",
        "ISYAT" to "İş Yatırım Ortaklığı",
        "IZENR" to "İzdemir Enerji Elektrik Üretim",
        "IZFAS" to "İzmir Fırça Sanayi ve Ticaret",
        "IZINV" to "İz Yatırım Holding",
        "IZMDC" to "İzmir Demir Çelik Sanayi",
        "JANTS" to "Jantsa Jant Sanayi ve Ticaret",
        "KAPLM" to "Kaplamin Ambalaj Sanayi ve Ticaret",
        "KAREL" to "Karel Elektronik Sanayi ve Ticaret",
        "KARSN" to "Karsan Otomotiv Sanayii ve Ticaret",
        "KARTN" to "Kartonsan Karton Sanayi ve Ticaret",
        "KARYE" to "Kartal Yenilenebilir Enerji Üretim",
        "KATMR" to "Katmerciler Araç Üstü Ekipman Sanayi",
        "KAYSE" to "Kayseri Şeker Fabrikası",
        "KBORU" to "Kuzey Boru A.Ş.",
        "KCAER" to "Kocaer Çelik Sanayi ve Ticaret",
        "KCHOL" to "Koç Holding A.Ş.",
        "KENT" to "Kent Gıda Maddeleri Sanayii ve Ticaret",
        "KERVN" to "Kervansaray Yatırım Holding",
        "KERVT" to "Kerevitaş Gıda Sanayi ve Ticaret",
        "KFEIN" to "Kafein Yazılım Hizmetleri",
        "KGYO" to "Koray Gayrimenkul Yatırım Ortaklığı",
        "KIMMR" to "Ersan Alışveriş Hizmetleri (Kim Market)",
        "KLKIM" to "Kalekim Kimyevi Maddeler Sanayi ve Ticaret",
        "KLMSN" to "Klimasan Klima Sanayi ve Ticaret",
        "KLNMA" to "Türkiye Kalkınma ve Yatırım Bankası",
        "KLRHO" to "Kiler Holding",
        "KLSER" to "Kaleseramik Çanakkale Kalebodur Seramik Sanayi",
        "KLSYN" to "Koleksiyon Mobilya Sanayi ve Ticaret",
        "KLYAS" to "Kalyon Güneş Teknolojileri",
        "KLYPV" to "Kalyon Fotovoltaik Güneş Teknolojileri",
        "KMPUR" to "Kimteks Poliüretan Sanayi ve Ticaret",
        "KNFRT" to "Konfrut Tarım A.Ş.",
        "KOCMT" to "Koç Metalurji",
        "KONKA" to "Konya Kağıt Sanayi ve Ticaret",
        "KONTR" to "Kontrolmatik Teknoloji Enerji ve Mühendislik",
        "KONYA" to "Konya Çimento Sanayii",
        "KOPOL" to "Koza Polyester Sanayi ve Ticaret",
        "KORDS" to "Kordsa Teknik Tekstil A.Ş.",
        "KOTON" to "Koton Mağazacılık Tekstil Sanayi ve Ticaret",
        "KOZAA" to "Koza Anadolu Metal Madencilik İşletmeleri",
        "KOZAL" to "Koza Altın İşletmeleri",
        "KRDMA" to "Kardemir Karabük Demir Çelik (A)",
        "KRDMB" to "Kardemir Karabük Demir Çelik (B)",
        "KRDMD" to "Kardemir Karabük Demir Çelik (D)",
        "KRONT" to "Kron Telekomünikasyon Hizmetleri",
        "KRPLS" to "Koroplast Temizlik Ambalaj Ürünleri",
        "KRSTL" to "Kristal Kola ve Meşrubat Sanayi",
        "KRTEK" to "Karsu Tekstil Sanayii ve Ticaret",
        "KRVGD" to "Kervan Gıda Sanayi ve Ticaret",
        "KSTUR" to "Kuştur Kuşadası Turizm Endüstrisi",
        "KTLEV" to "Katılımevim Tasarruf Finansman",
        "KTSKR" to "Kütahya Şeker Fabrikası",
        "KUTPO" to "Kütahya Porselen Sanayi",
        "KUVVA" to "Kuvva Gıda Ticaret ve Yatırımlar",
        "KUYAS" to "Kuyaş Yatırım A.Ş.",
        "KZBGY" to "Kızılbük Gayrimenkul Yatırım Ortaklığı",
        "KZGYO" to "Kuzugrup Gayrimenkul Yatırım Ortaklığı",
        "LIDER" to "Lider Faktoring",
        "LIDFA" to "Lider Faktoring",
        "LILAK" to "Lila Kağıt Sanayi ve Ticaret",
        "LINK" to "Link Bilgisayar Sistemleri Yazılımı",
        "LKMNH" to "Lokman Hekim Engürüsağ Sağlık Turizm",
        "LMKDC" to "Limak Doğu Anadolu Çimento Sanayi",
        "LOGAS" to "Logo Siber Güvenlik",
        "LOGO" to "Logo Yazılım Sanayi ve Ticaret",
        "LRSHL" to "Larus Holding",
        "LRSHO" to "Larus Holding",
        "LUKSK" to "Lüks Kadife Ticaret ve Sanayii",
        "LXGYO" to "Lux Gayrimenkul Yatırım Ortaklığı",
        "LYDHO" to "Lydian Holding",
        "LYDYE" to "Lydian Enerji",
        "MAALT" to "Marmaris Altınyunus Turistik Tesisleri",
        "MACKO" to "Maçkolik İnternet Hizmetleri",
        "MAGEN" to "Margün Alternatif Enerji Üretim",
        "MAKIM" to "Makim Makina Teknolojileri Sanayi",
        "MAKTK" to "Makina Takım Endüstrisi",
        "MANAS" to "Manas Enerji Yönetimi Sanayi ve Ticaret",
        "MARBL" to "Tureks Turunç Madencilik (Marble)",
        "MARKA" to "Marka Yatırım Holding",
        "MARMR" to "Marmara Çimento",
        "MARTI" to "Martı Otel İşletmeleri",
        "MAVI" to "Mavi Giyim Sanayi ve Ticaret",
        "MCARD" to "Multi Kart Teknolojileri",
        "MEDTR" to "Medical Park (Tıbbi Tesisler Sağlık)",
        "MEGAP" to "Mega Polietilen Köpük Sanayi ve Ticaret",
        "MEGMT" to "Mega Metal Sanayi ve Ticaret",
        "MEKAG" to "Meka Beton Santralleri İmalat Sanayi",
        "MEPET" to "Mepet Metro Petrol ve Tesisleri Sanayi",
        "MERCN" to "Mercan Kimya Sanayi ve Ticaret",
        "MERIT" to "Merit Turizm ve Yatırım İşletmeciliği",
        "MERKO" to "Merko Gıda Sanayi ve Ticaret",
        "METRO" to "Metro Ticari ve Mali Yatırımlar Holding",
        "METUR" to "Metemtur Otelcilik ve Turizm İşletmeleri",
        "MEYSU" to "Meysu Gıda Sanayi ve Ticaret",
        "MGROS" to "Migros Ticaret A.Ş.",
        "MHRGY" to "MHR Gayrimenkul Yatırım Ortaklığı",
        "MIATK" to "Mia Teknoloji A.Ş.",
        "MIPAZ" to "Milpa Ticari ve Sınai Ürünler Pazarlama",
        "MMCAS" to "MMC Sanayi ve Ticari Yatırımlar",
        "MNDRS" to "Menderes Tekstil Sanayi ve Ticaret",
        "MNDTR" to "Mondi Turkey Oluklu Mukavva Kağıt",
        "MOBTL" to "Mobiltel İletişim Hizmetleri Sanayi",
        "MOGAN" to "Mogan Enerji Yatırım Holding",
        "MOPAS" to "Mopaş Marketçilik Gıda Sanayi",
        "MPARK" to "MLP Sağlık Hizmetleri (Medical Park)",
        "MRGYO" to "Martı Gayrimenkul Yatırım Ortaklığı",
        "MRSHL" to "Marshall Boya ve Vernik Sanayii",
        "MSGYO" to "Mistral Gayrimenkul Yatırım Ortaklığı",
        "MTRKS" to "Matriks Bilgi Dağıtım Hizmetleri",
        "MTRYO" to "Metro Yatırım Ortaklığı",
        "MZHLD" to "Mazhar Zorlu Holding",
        "NATEN" to "Naturel Yenilenebilir Enerji Ticaret",
        "NETAS" to "Netaş Telekomünikasyon",
        "NETCD" to "Netcad Yazılım",
        "NIBAS" to "Niğbaş Niğde Beton Sanayi ve Ticaret",
        "NTGAZ" to "Naturelgaz Sanayi ve Ticaret",
        "NTHOL" to "Net Holding",
        "NUGYO" to "Nurol Gayrimenkul Yatırım Ortaklığı",
        "NUHCM" to "Nuh Çimento Sanayi",
        "OBAMS" to "Oba Makarnacılık Sanayi ve Ticaret",
        "OBASE" to "Obase Bilgisayar ve Danışmanlık Hizmetleri",
        "ODAS" to "Odaş Elektrik Üretim Sanayi Ticaret",
        "ODINE" to "Odine Solutions Teknoloji Ticaret",
        "OFSYM" to "Ofis Yem Gıda Sanayi ve Ticaret",
        "ONCSM" to "Oncosem Onkolojik Sistemler Sanayi",
        "ONRYT" to "Onur Yüksek Teknoloji",
        "ORCAY" to "Ortaköy Çay Sanayi ve Ticaret",
        "ORGE" to "Orge Enerji Elektrik Taahhüt",
        "ORMA" to "Orma Orman Mahsulleri İntegre Sanayi",
        "OSMEN" to "Osmanlı Yatırım Menkul Değerler",
        "OSTIM" to "Ostim Endüstriyel Yatırımlar ve İşletme",
        "OTKAR" to "Otokar Otomotiv ve Savunma Sanayi",
        "OTTO" to "Otto Holding",
        "OYAKC" to "Oyak Çimento Fabrikaları",
        "OYAYO" to "Oyak Yatırım Ortaklığı",
        "OYLUM" to "Oylum Sınai Yatırımlar",
        "OYYAT" to "Oyak Yatırım Menkul Değerler",
        "OZATD" to "Özata Denizcilik Sanayi ve Ticaret",
        "OZGYO" to "Özderici Gayrimenkul Yatırım Ortaklığı",
        "OZKGY" to "Özak Gayrimenkul Yatırım Ortaklığı",
        "OZRDN" to "Özerden Plastik Sanayi ve Ticaret",
        "OZSUB" to "Özsu Balık Üretimi",
        "OZYSR" to "Özyaşar Tel ve Çok Amaçlı Tel Sanayi",
        "PAGYO" to "Panora Gayrimenkul Yatırım Ortaklığı",
        "PAHOL" to "Pasifik Holding",
        "PAMEL" to "Pamukova Elektrik Üretim",
        "PAPA" to "Papara Elektronik Para",
        "PAPIL" to "Papilon Savunma Güvenlik Sistemleri",
        "PARSN" to "Parsan Makina Parçaları Sanayii",
        "PASEU" to "Pasifik Eurasia Lojistik Dış Ticaret",
        "PATEK" to "Pasifik Donanım ve Yazılım Bilgi Teknolojileri",
        "PCILT" to "Pc İletişim ve Medya Hizmetleri Sanayi",
        "PEGYO" to "Pera Gayrimenkul Yatırım Ortaklığı",
        "PEKGY" to "Peker Gayrimenkul Yatırım Ortaklığı",
        "PENGD" to "Penguen Gıda Sanayi",
        "PENTA" to "Penta Teknoloji Ürünleri Dağıtım",
        "PETKM" to "Petkim Petrokimya Holding",
        "PETUN" to "Pınar Entegre Et ve Un Sanayii",
        "PGSUS" to "Pegasus Hava Taşımacılığı",
        "PINSU" to "Pınar Su ve İçecek Sanayi",
        "PKART" to "Plastikkart Akıllı Kart İletişim Sistemleri",
        "PKENT" to "Petrokent Turizm",
        "PLTUR" to "Platform Turizm Taşımacılık",
        "PNLSN" to "Panelsan Çatı Cephe Sistemleri Sanayi",
        "PNSUT" to "Pınar Süt Mamülleri Sanayii",
        "POLHO" to "Polisan Holding",
        "POLTK" to "Politeknik Metal Sanayi ve Ticaret",
        "PRDGS" to "Pardus Girişim Sermayesi Yatırım Ortaklığı",
        "PRKAB" to "Türk Prysmian Kablo ve Sistemleri",
        "PRKME" to "Park Elektrik Üretim Madencilik Sanayi",
        "PRZMA" to "Prizma Pres Matbaacılık Yayıncılık",
        "PSDTC" to "Pergamon Status Dış Ticaret",
        "PSGYO" to "Pasifik Gayrimenkul Yatırım Ortaklığı",
        "QNBFK" to "QNB Finans Finansal Kiralama",
        "QNBTR" to "QNB Türkiye (QNB Finansbank)",
        "QUAGR" to "Qua Granite Hayal Yapı ve Ürünleri",
        "RALYH" to "Ral Yatırım Holding",
        "RAYSG" to "Ray Sigorta",
        "RAYYS" to "Ray Sigorta",
        "REEDR" to "Reeder Teknoloji Sanayi ve Ticaret",
        "RGYAS" to "Rönesans Gayrimenkul Yatırım",
        "RNPOL" to "Rainbow Polikarbonat Sanayi ve Ticaret",
        "RODRG" to "Rodrigo Tekstil Sanayi ve Ticaret",
        "ROYAL" to "Royal Halı İplik Tekstil Mobilya",
        "RTALB" to "RTA Laboratuvarları Biyolojik Ürünler İlaç",
        "RUBNS" to "Rubenis Mensucat Sanayi ve Ticaret",
        "RUZYE" to "Rüzgar Yenilenebilir Enerji",
        "RYGYO" to "Reysaş Gayrimenkul Yatırım Ortaklığı",
        "RYSAS" to "Reysaş Taşımacılık ve Lojistik Ticaret",
        "SAFKR" to "Safkar Ege Soğutmacılık Klima Soğuk Hava",
        "SAHOL" to "Hacı Ömer Sabancı Holding",
        "SAMAT" to "Saray Matbaacılık Kağıtçılık Kırtasiyecilik",
        "SANEL" to "San-El Mühendislik Elektrik Taahhüt",
        "SANFM" to "Sanifoam Sünger Sanayi ve Ticaret",
        "SANKO" to "Sanko Pazarlama İthalat İhracat",
        "SARKY" to "Sarkuysan Elektrolitik Bakır Sanayii",
        "SASA" to "SASA Polyester Sanayi",
        "SAYAS" to "Say Yenilenebilir Enerji Ekipmanları Sanayi",
        "SDTTR" to "SDT Uzay ve Savunma Teknolojileri",
        "SEGMN" to "Seğmen Kardeşler Gıda Üretim",
        "SEGYO" to "Şeker Gayrimenkul Yatırım Ortaklığı",
        "SEKFK" to "Şeker Finansal Kiralama",
        "SEKUR" to "Sekuro Plastik Ambalaj Sanayi",
        "SELEC" to "Selçuk Ecza Deposu Ticaret ve Sanayi",
        "SELGD" to "Selçuk Gıda Endüstri İhracat İthalat",
        "SELVA" to "Selva Gıda Sanayi",
        "SERNT" to "Serenat Tekstil Sanayi",
        "SEYKM" to "Seyitler Kimya Sanayi",
        "SILVR" to "Silverline Endüstri ve Ticaret",
        "SISE" to "Türkiye Şişe ve Cam Fabrikaları",
        "SKBNK" to "Şekerbank T.A.Ş.",
        "SKTAS" to "Söktaş Tekstil Sanayi ve Ticaret",
        "SKYLP" to "Sky Alp Havacılık",
        "SKYMD" to "Şeker Yatırım Menkul Değerler",
        "SMART" to "Smartiks Yazılım",
        "SMRTG" to "Smart Güneş Enerjisi Teknolojileri",
        "SMRVA" to "Sümer Varlık Yönetim",
        "SNGYO" to "Sinpaş Gayrimenkul Yatırım Ortaklığı",
        "SNICA" to "Sanica Isı Sanayi",
        "SNKPA" to "Sanko Pazarlama",
        "SNPAM" to "Sönmez Pamuklu Sanayii",
        "SODSN" to "Sodaş Sodyum Sanayii",
        "SOKE" to "Söke Değirmencilik Sanayi ve Ticaret",
        "SOKM" to "Şok Marketler Ticaret",
        "SONME" to "Sönmez Filament Sentetik İplik Sanayii",
        "SRVGY" to "Servet Gayrimenkul Yatırım Ortaklığı",
        "SUMAS" to "Sumaş Suni Tahta ve Mobilya Sanayi",
        "SUNTK" to "Sun Tekstil Sanayi ve Ticaret",
        "SURGY" to "Sur Tatil Evleri Gayrimenkul Yatırım Ortaklığı",
        "SUWEN" to "Suwen Tekstil Sanayi ve Pazarlama",
        "TABGD" to "TAB Gıda Sanayi ve Ticaret",
        "TARKM" to "Tarkim Bitki Koruma Sanayi ve Ticaret",
        "TATEN" to "Tatlıpınar Enerji Üretim",
        "TATGD" to "Tat Gıda Sanayi",
        "TAVHL" to "TAV Havalimanları Holding",
        "TCELL" to "Turkcell İletişim Hizmetleri",
        "TDGYO" to "Trend Gayrimenkul Yatırım Ortaklığı",
        "TEKTU" to "Tek-Art İnşaat Ticaret Turizm Sanayi",
        "TERA" to "Tera Yatırım Menkul Değerler",
        "TETMT" to "Tetamat Gıda Yatırımları",
        "TGSAS" to "TGS Dış Ticaret",
        "THYAO" to "Türk Hava Yolları A.O.",
        "TIRE" to "Mondi Tire Kutsan Kağıt ve Ambalaj",
        "TKFEN" to "Tekfen Holding",
        "TKNSA" to "Teknosa İç ve Dış Ticaret",
        "TLSAS" to "Tilaş Lojistik",
        "TMPOL" to "Temapol Polimer Plastik ve İnşaat Sanayi",
        "TMSN" to "Tümosan Motor ve Traktör Sanayi",
        "TOASO" to "Tofaş Türk Otomobil Fabrikası",
        "TRCAS" to "Turcas Petrol",
        "TRGYO" to "Torunlar Gayrimenkul Yatırım Ortaklığı",
        "TRILC" to "Türk İlaç ve Serum Sanayi",
        "TSKB" to "Türkiye Sınai Kalkınma Bankası",
        "TSPOR" to "Trabzonspor Sportif Yatırım ve Ticaret",
        "TTKOM" to "Türk Telekomünikasyon A.Ş.",
        "TTRAK" to "Türk Traktör ve Ziraat Makineleri",
        "TUCLK" to "Tuğçelik Alüminyum ve Metal Mamülleri",
        "TUKAS" to "Tukaş Gıda Sanayi ve Ticaret",
        "TUPRS" to "TÜPRAŞ - Türkiye Petrol Rafinerileri",
        "TUREX" to "Tureks Turizm Taşımacılık",
        "TURGG" to "Türker Proje Gayrimenkul ve Yatırım",
        "TURSG" to "Türkiye Sigorta A.Ş.",
        "UFUK" to "Ufuk Yatırım Yönetim ve Gayrimenkul",
        "ULAS" to "Ulaşlar Turizm Yatırımları ve Dayanıklı Tüketim",
        "ULKER" to "Ülker Bisküvi Sanayi",
        "ULUFA" to "Ulusal Faktoring",
        "ULUSE" to "Ulusoy Elektrik İmalat Taahhüt ve Ticaret",
        "ULUN" to "Ulusoy Un Sanayi ve Ticaret",
        "UMPAS" to "Umpaş Holding",
        "UNLU" to "Ünlü Yatırım Holding",
        "USAK" to "Uşak Seramik Sanayi",
        "VAKBN" to "Türkiye Vakıflar Bankası (VakıfBank)",
        "VAKFN" to "Vakıf Finansal Kiralama",
        "VAKKO" to "Vakko Tekstil ve Hazır Giyim Sanayi",
        "VANGD" to "Vanet Gıda Sanayi İç ve Dış Ticaret",
        "VBTYZ" to "VBT Yazılım A.Ş.",
        "VERTU" to "Verusaturk Girişim Sermayesi Yatırım Ortaklığı",
        "VERUS" to "Verusa Holding",
        "VESBE" to "Vestel Beyaz Eşya Sanayi ve Ticaret",
        "VESTL" to "Vestel Elektronik Sanayi ve Ticaret",
        "VKGYO" to "Vakıf Gayrimenkul Yatırım Ortaklığı",
        "VKING" to "Viking Kağıt ve Selüloz",
        "YAPRK" to "Yaprak Süt ve Besi Çiftlikleri Sanayi",
        "YATAS" to "Yataş Yatak ve Yorgan Sanayi ve Ticaret",
        "YAYLA" to "Yayla Enerji Üretim Turizm ve İnşaat",
        "YBTAS" to "Yibitaş Yozgat İşçi Birliği İnşaat Malzemeleri",
        "YEOTK" to "YEO Teknoloji Enerji ve Endüstri",
        "YESIL" to "Yeşil Yatırım Holding",
        "YGGYO" to "Yeni Gimat Gayrimenkul Yatırım Ortaklığı",
        "YGYO" to "Yeşil Gayrimenkul Yatırım Ortaklığı",
        "YKBNK" to "Yapı ve Kredi Bankası A.Ş.",
        "YKSLN" to "Yükselen Çelik",
        "YONGA" to "Yonga Mobilya Sanayi ve Ticaret",
        "YOTAS" to "Yotaş Gayrimenkul",
        "YUNSA" to "Yünsa Yünlü Sanayi ve Ticaret",
        "YYAPI" to "Yeşil Yapı Endüstrisi",
        "YYLGD" to "Yayla Agro Gıda Sanayi ve Ticaret",
        "ZEDUR" to "Zedur Enerji Elektrik Üretim",
        "ZOREN" to "Zorlu Enerji Elektrik Üretim",
        "ZRGYO" to "Ziraat Gayrimenkul Yatırım Ortaklığı"
    )

    /**
     * Verilen sembol veya mevcut ada göre şirketin uzun/tam ismini döner.
     * Sembol .IS uzantılı da olsa (örn: AEFES.IS) temizlenerek aranır.
     * Eğer listede bulunamazsa ve fallbackName sembolden farklı bir isimse fallbackName döner,
     * aksi halde temiz sembol kodunu döner.
     */
    fun getCompanyName(symbol: String?, fallbackName: String? = null): String {
        if (symbol.isNullOrBlank()) return fallbackName.orEmpty()
        val cleanSymbol = symbol.trim().uppercase().substringBefore(".")
        
        companyNames[cleanSymbol]?.let { return it }

        if (!fallbackName.isNullOrBlank()) {
            val cleanFallback = fallbackName.trim()
            if (!cleanFallback.equals(cleanSymbol, ignoreCase = true) &&
                !cleanFallback.equals(symbol.trim(), ignoreCase = true)
            ) {
                return cleanFallback
            }
        }

        return cleanSymbol
    }

    /**
     * Arama sorgusuna uyan sembolleri veya şirket unvanlarını bulur.
     * Örneğin "hava" -> ["THYAO.IS", "PGSUS.IS", "TAVHL.IS"]
     */
    fun findSymbolsByNameQuery(query: String): List<String> {
        if (query.isBlank()) return emptyList()
        val q = query.trim().lowercase()
        val results = mutableListOf<String>()
        companyNames.filter { (symbol, name) ->
            symbol.lowercase().contains(q) || name.lowercase().contains(q)
        }.keys.forEach {
            results.add(it)
            results.add("$it.IS")
        }
        return results
    }
}
